package utilidad;

import inicio.InicioApp;
import java.awt.event.*;
import javax.swing.*;

public class SeleccionarTarjetasUsuario extends javax.swing.JFrame {

    public SeleccionarTarjetasUsuario() {
        initComponents();
        inicializarForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFRegistroInicial = new utilidad.componentes.MiJFTFDecimal();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMConfiguracion = new javax.swing.JMenu();
        jMAyuda = new javax.swing.JMenu();
        jMIPaginaInicio = new javax.swing.JMenuItem();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form");
        setResizable(false);
        getContentPane().setLayout(null);
        jLTitulo.setFont(new java.awt.Font("Arial", 1, 24));
        jLTitulo.setText("Seleccionar Tarjetas Usuario");
        jLTitulo.setToolTipText("");
        jLTitulo.setName("jLTitulo");
        getContentPane().add(jLTitulo);
        jLTitulo.setBounds(10, 10, 430, 29);
        jSeparator1.setName("jSeparator1");
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 410, 10);
        jBSeleccionar.setText("Seleccionar");
        jBSeleccionar.setName("jBSeleccionar");
        jBSeleccionar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(jBSeleccionar);
        jBSeleccionar.setBounds(110, 120, 140, 23);
        jLabel1.setText("Imprimir Desde la Posición:");
        jLabel1.setName("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 180, 20);
        jTFRegistroInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFRegistroInicial.setText("1");
        jTFRegistroInicial.setName("jTFRegistroInicial");
        getContentPane().add(jTFRegistroInicial);
        jTFRegistroInicial.setBounds(260, 80, 40, 20);
        jMenuBar1.setName("jMenuBar1");
        jMConfiguracion.setText("Configuración");
        jMConfiguracion.setName("jMConfiguracion");
        jMenuBar1.add(jMConfiguracion);
        jMAyuda.setText("Ayuda");
        jMAyuda.setName("jMAyuda");
        jMIPaginaInicio.setText("Página de Inicio");
        jMIPaginaInicio.setName("jMIPaginaInicio");
        jMIPaginaInicio.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPaginaInicioActionPerformed(evt);
            }
        });
        jMAyuda.add(jMIPaginaInicio);
        jMenuBar1.add(jMAyuda);
        setJMenuBar(jMenuBar1);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 409) / 2, (screenSize.height - 215) / 2, 409, 215);
    }

    private void jBSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {
        seleccionar();
    }

    private void jMIPaginaInicioActionPerformed(java.awt.event.ActionEvent evt) {
        irPaginaInicio();
    }

    private void inicializarForm() {
        this.setTitle("Seleccionar Tarjetas Usuario");
        Util.cambiarIcono(this);
    }

    private void irPaginaInicio() {
        InicioApp.cerrarVentanasAbiertas();
        this.dispose();
    }

    private void seleccionar() {
        if (jTFRegistroInicial.getValue().intValue() > 0) {
            registroInicial = jTFRegistroInicial.getValue().intValue();
            this.dispose();
        }
    }

    public Integer registroInicial = null;

    @Override
    protected JRootPane createRootPane() {
        JRootPane rootPane = new JRootPane();
        Action actionEscape = new AbstractAction() {

            public void actionPerformed(ActionEvent actionEvent) {
                dispose();
            }
        };
        Action actionEnter = new AbstractAction() {

            public void actionPerformed(ActionEvent actionEvent) {
                seleccionar();
            }
        };
        KeyStroke strokeEscape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        KeyStroke strokeEnter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        rootPane.registerKeyboardAction(actionEscape, strokeEscape, JComponent.WHEN_IN_FOCUSED_WINDOW);
        rootPane.registerKeyboardAction(actionEnter, strokeEnter, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }

    private javax.swing.ButtonGroup buttonGroup1;

    private javax.swing.JButton jBSeleccionar;

    private javax.swing.JLabel jLTitulo;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JMenu jMAyuda;

    private javax.swing.JMenu jMConfiguracion;

    private javax.swing.JMenuItem jMIPaginaInicio;

    private javax.swing.JMenuBar jMenuBar1;

    private javax.swing.JSeparator jSeparator1;

    private utilidad.componentes.MiJFTFDecimal jTFRegistroInicial;
}
