package com.rapidminer;

import com.rapidminer.gui.tools.VersionNumber;

/** This
           class is generated by the ant target "version.updateFiles" to ensure the correct
           version number in RapidMiner. */
public class RapidMinerVersion extends VersionNumber {

    public RapidMinerVersion() {
        super("5.1.017");
    }
}
