package gui;

import java.util.ArrayList;
import java.util.List;
import manager.Commands;

/**
 *
 * @author  Marco Celesti
 */
public class IntestazioneJFrame extends javax.swing.JFrame {

    private static IntestazioneJFrame intestazioneJFrame = null;

    private boolean initialized = false;

    private List<String> righe;

    /**
     * Creates new form HelpJFrame
     */
    private IntestazioneJFrame() {
    }

    /**
     * La classe implementa il pattern Singleton.
     * @return l'istanza di tipo statico della classe
     */
    public static IntestazioneJFrame getInstance() {
        if (intestazioneJFrame == null) {
            intestazioneJFrame = new IntestazioneJFrame();
        }
        return intestazioneJFrame;
    }

    public void init(boolean nuovaIstanza) {
        if (!initialized) {
            initComponents();
            initialized = true;
        }
        initValues();
    }

    public List<String> getIntestazione() {
        return righe;
    }

    public void setIntestazione(List<String> righe) {
        this.righe = righe;
    }

    private void initValues() {
        if (righe.size() == 5) {
            primaRigajTextField.setText(righe.get(0));
            secondaRigajTextField.setText(righe.get(1));
            terzaRigajTextField.setText(righe.get(2));
            quartaRigajTextField.setText(righe.get(3));
            quintaRigajTextField.setText(righe.get(4));
        } else {
            primaRigajTextField.setText("");
            secondaRigajTextField.setText("");
            terzaRigajTextField.setText("");
            quartaRigajTextField.setText("");
            quintaRigajTextField.setText("");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salvajButton = new javax.swing.JButton();
        terzaRigajTextField = new javax.swing.JTextField();
        secondaRigajTextField = new javax.swing.JTextField();
        primaRigajTextField = new javax.swing.JTextField();
        cancellajButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quartaRigajTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quintaRigajTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpjMenu = new javax.swing.JMenu();
        helpjMenuItem = new javax.swing.JMenuItem();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imposta l'intestazione per le ricevute");
        setResizable(false);
        jLabel1.setText("Prima riga:");
        jLabel2.setText("Seconda riga:");
        jLabel3.setText("Terza riga:");
        salvajButton.setText("Salva");
        salvajButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvajButtonActionPerformed(evt);
            }
        });
        cancellajButton.setText("Cancella");
        cancellajButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellajButtonActionPerformed(evt);
            }
        });
        jLabel4.setText("Quarta riga:");
        jLabel5.setText("Quinta riga:");
        helpjMenu.setText("Help");
        helpjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpjMenuItem.setText("Help");
        helpjMenuItem.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpjMenuItemActionPerformed(evt);
            }
        });
        helpjMenu.add(helpjMenuItem);
        jMenuBar1.add(helpjMenu);
        setJMenuBar(jMenuBar1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jLabel1).addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel3).addComponent(salvajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jLabel4).addComponent(jLabel5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(quintaRigajTextField).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(terzaRigajTextField).addComponent(secondaRigajTextField).addComponent(primaRigajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)).addComponent(cancellajButton, javax.swing.GroupLayout.Alignment.TRAILING)).addComponent(quartaRigajTextField)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(primaRigajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(secondaRigajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(terzaRigajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(quartaRigajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(quintaRigajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(cancellajButton).addComponent(salvajButton)).addContainerGap()));
        pack();
    }

    private void salvajButtonActionPerformed(java.awt.event.ActionEvent evt) {
        righe.clear();
        righe.add(primaRigajTextField.getText());
        righe.add(secondaRigajTextField.getText());
        righe.add(terzaRigajTextField.getText());
        righe.add(quartaRigajTextField.getText());
        righe.add(quintaRigajTextField.getText());
        firePropertyChange(Commands.UPSERT_INTESTAZIONE.getCommand(), null, null);
    }

    private void cancellajButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void helpjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        firePropertyChange(Commands.HELP_INTESTAZIONE.getCommand(), null, null);
    }

    private javax.swing.JButton cancellajButton;

    private javax.swing.JMenu helpjMenu;

    private javax.swing.JMenuItem helpjMenuItem;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JMenuBar jMenuBar1;

    private javax.swing.JTextField primaRigajTextField;

    private javax.swing.JTextField quartaRigajTextField;

    private javax.swing.JTextField quintaRigajTextField;

    private javax.swing.JButton salvajButton;

    private javax.swing.JTextField secondaRigajTextField;

    private javax.swing.JTextField terzaRigajTextField;
}
