package edu.unibi.agbi.biodwh.entity.kegg.pathway;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KeggPathwayDisease generated by hbm2java
 */
@Entity(name = "kegg_pathway_disease")
@Table(name = "kegg_pathway_disease")
public class KeggPathwayDisease implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = -6770399429785909660L;

    private KeggPathwayDiseaseId id;

    private KeggPathway keggPathway;

    public KeggPathwayDisease() {
    }

    public KeggPathwayDisease(KeggPathwayDiseaseId id, KeggPathway keggPathway) {
        this.id = id;
        this.keggPathway = keggPathway;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "entry", column = @Column(name = "entry", nullable = false)), @AttributeOverride(name = "disease", column = @Column(name = "disease", nullable = false)), @AttributeOverride(name = "name", column = @Column(name = "name", nullable = false)) })
    public KeggPathwayDiseaseId getId() {
        return this.id;
    }

    public void setId(KeggPathwayDiseaseId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "entry", nullable = false, insertable = false, updatable = false)
    public KeggPathway getKeggPathway() {
        return this.keggPathway;
    }

    public void setKeggPathway(KeggPathway keggPathway) {
        this.keggPathway = keggPathway;
    }
}
