package clubmixer.client.ui.main;

import com.slychief.clubmixer.client.commons.guielements.panels.SongEntryPanel;
import clubmixer.client.control.ClientController;
import clubmixer.client.handler.playlistChange.PlaylistChangeEvent;
import clubmixer.client.handler.playlistChange.PlaylistChangeListener;
import com.slychief.clubmixer.client.commons.guielements.menu.SimpleSonglabelMenu;
import com.slychief.clubmixer.server.library.entities.SongArray;
import org.jdesktop.swingx.VerticalLayout;

/**
 *
 * @author Alexander Schindler
 */
public class NextSongsPanel extends javax.swing.JPanel implements PlaylistChangeListener {

    private SongEntryPanel entry1;

    private SongEntryPanel entry2;

    private SongEntryPanel entry3;

    private SongEntryPanel entry4;

    /** Creates new form NextSongsPanel */
    public NextSongsPanel() {
        initComponents();
        initNextSongsPanel();
        ClientController.getInstance().addListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(clubmixer.client.ClubmixerClientApp.class).getContext().getResourceMap(NextSongsPanel.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("Form.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("Form.border.titleColor")));
        setMinimumSize(new java.awt.Dimension(100, 0));
        setName("Form");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 384, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 270, Short.MAX_VALUE));
    }

    private void initNextSongsPanel() {
        SimpleSonglabelMenu menu = new SimpleSonglabelMenu();
        VerticalLayout vl = new VerticalLayout();
        vl.setGap(3);
        this.setLayout(vl);
        entry1 = new SongEntryPanel();
        entry1.addMenu(menu);
        this.add(entry1);
        entry2 = new SongEntryPanel();
        entry2.addMenu(menu);
        this.add(entry2);
        entry3 = new SongEntryPanel();
        entry3.addMenu(menu);
        this.add(entry3);
        entry4 = new SongEntryPanel();
        entry4.addMenu(menu);
        this.add(entry4);
    }

    @Override
    public void onPlaylistChanged(PlaylistChangeEvent se) {
        SongArray nextsongs = se.getNextSongs();
        entry1.updateSongInfo(nextsongs.getItem().get(0));
        entry2.updateSongInfo(nextsongs.getItem().get(1));
        entry3.updateSongInfo(nextsongs.getItem().get(2));
        entry4.updateSongInfo(nextsongs.getItem().get(3));
    }
}
