package org.hironico.dbtool2.querymanager.svn;

import javax.swing.JFileChooser;

/**
 * Panel qui modélise la gui pour la configuration du query manager.
 * @author hironico
 * @since 2.2.0
 */
public class QueryManagerConfigPanel extends javax.swing.JPanel {

    /** Creates new form QueryManagerConfigPanel */
    public QueryManagerConfigPanel() {
        initComponents();
        savedQueriesDirChooser.getFileChooser().setMultiSelectionEnabled(false);
        savedQueriesDirChooser.getFileChooser().setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     *
     * @return un objet QueryManagerConfig correctement configuré pour refléter la GUI.
     * @since 2.2.0
     */
    public QueryManagerConfig getQueryManagerConfig() {
        QueryManagerConfig config = new QueryManagerConfig();
        config.setSavedQueryDirectory(savedQueriesDirChooser.getSelectedFileName());
        config.setSvnClientConfig(svnClientConfigPanel.getSvnClientConfig());
        config.setUsePlainText(chkUsePLainText.isSelected());
        return config;
    }

    /**
     * Permet d'afficher la config du query manager dans la GUI.
     * @param config le config à afficher.
     * @since 2.2.0
     */
    public void showQueryManagerConfig(QueryManagerConfig config) {
        savedQueriesDirChooser.setSelectedFileName(config.getSavedQueryDirectory());
        chkUsePLainText.setSelected(config.isUsePlainText());
        svnClientConfigPanel.displaySvnClientConfig(config.getSvnClientConfig());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        savedQueriesDirChooser = new org.hironico.gui.file.FileChooserPanel();
        bannerTitle = new com.jidesoft.dialog.BannerPanel();
        svnClientConfigPanel = new org.hironico.svnclient.gui.config.SVNClientConfigPanel();
        titledSeparatorSvn = new org.jdesktop.swingx.JXTitledSeparator();
        chkUsePLainText = new javax.swing.JCheckBox();
        setLayout(new java.awt.GridBagLayout());
        savedQueriesDirChooser.setLabel("Saved queries directory:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(savedQueriesDirChooser, gridBagConstraints);
        bannerTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bannerTitle.setEndColor(this.getBackground());
        bannerTitle.setPreferredSize(new java.awt.Dimension(194, 100));
        bannerTitle.setStartColor(java.awt.Color.white);
        bannerTitle.setSubtitle("Select a directory where to save you queries. You can also setup a subversion client in order to use SVN version control for your queries.");
        bannerTitle.setTitle("Query manager configuration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(bannerTitle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(svnClientConfigPanel, gridBagConstraints);
        titledSeparatorSvn.setTitle("Subversion setup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(titledSeparatorSvn, gridBagConstraints);
        chkUsePLainText.setText("Use plain text when saving queries to files");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(chkUsePLainText, gridBagConstraints);
    }

    private com.jidesoft.dialog.BannerPanel bannerTitle;

    private javax.swing.JCheckBox chkUsePLainText;

    private org.hironico.gui.file.FileChooserPanel savedQueriesDirChooser;

    private org.hironico.svnclient.gui.config.SVNClientConfigPanel svnClientConfigPanel;

    private org.jdesktop.swingx.JXTitledSeparator titledSeparatorSvn;
}
