package library.corba;

/**
* library/corba/BookedItemShort.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/CORBALibrary.idl
* Monday, July 12, 2010 5:38:18 PM CEST
*/
public final class BookedItemShort implements org.omg.CORBA.portable.IDLEntity {

    public long id = (long) 0;

    public int itemID = (int) 0;

    public boolean status = false;

    public library.corba.DocumentDescriptionShort descriptionShort = null;

    public BookedItemShort() {
    }

    public BookedItemShort(long _id, int _itemID, boolean _status, library.corba.DocumentDescriptionShort _descriptionShort) {
        id = _id;
        itemID = _itemID;
        status = _status;
        descriptionShort = _descriptionShort;
    }
}
