package it.bfp.sark.sql.input.postgresql;

import it.bfp.sark.common.NameFormatter;
import it.bfp.sark.sql.input.SqlInput;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.apache.commons.lang.StringUtils;

/**
 * 
 * @author BFP
 */
public class PostgreSqlInput extends SqlInput {

    @Override
    protected String getTableName(String tableOwner, String tableName) {
        return NameFormatter.toClassName(tableName);
    }

    @Override
    protected boolean isValidTable(String tableOwner) throws SQLException {
        return StringUtils.equalsIgnoreCase(tableOwner, jdbcConnect.getSchema());
    }

    @Override
    protected boolean isAutoGenerated(ResultSet rsColumns, String tableName, String columnName) throws SQLException {
        return rsColumns.getString("IS_AUTOINCREMENT").equalsIgnoreCase("YES");
    }
}
