package pt.ips.estsetubal.mig.academicCloud.client.service;

import pt.ips.estsetubal.mig.academicCloud.shared.dto.SessionDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.CompetenceCourseDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.CompetenceCourseInformationDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.CurricularCourseDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.DegreeCurricularPlanDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.DegreeDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.domain.degree.DepartmentDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.CreateCompetenceCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.CreateCurricularCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.CreateDegreeCurricularPlanViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.CreateDegreeViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DeleteCompetenceCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DeleteCurricularCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DeleteDegreeCurricularPlanViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DeleteDegreeViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DetailCompetenceCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DetailCurricularCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DetailDegreeCurricularPlanViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.DetailDegreeViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.EditCompetenceCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.EditCurricularCourseViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.EditDegreeCurricularPlanViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.EditDegreeViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchCompetenceCourseCriteriaDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchCompetenceCourseResultDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchCompetenceCourseCriteriaViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchDegreeCriteriaDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchDegreeCriteriaViewInitDataDTO;
import pt.ips.estsetubal.mig.academicCloud.shared.dto.view.curricularOffice.SearchDegreeResultDTO;
import com.google.gwt.user.client.rpc.AsyncCallback;

/**
 * Service asynchronous interface for the curricular office module.<br/>
 * This class is autogenerated and maintained by the IDE, so it's methods don't
 * have javadoc.
 * 
 * @author António Casqueiro
 */
public interface CurricularOfficeServiceAsync {

    void getSearchCompetenceCourseViewInitData(SessionDTO sessionInfo, AsyncCallback<SearchCompetenceCourseCriteriaViewInitDataDTO> callback);

    void searchCompetenceCourses(SessionDTO sessionInfo, SearchCompetenceCourseCriteriaDTO param, AsyncCallback<SearchCompetenceCourseResultDTO> callback);

    void storeCompetenceCourse(SessionDTO sessionInfo, CompetenceCourseDTO param, AsyncCallback<Void> callback);

    void getCreateCompetenceCourseViewInitData(SessionDTO sessionInfo, AsyncCallback<CreateCompetenceCourseViewInitDataDTO> callback);

    void getEditCompetenceCourseViewInitData(SessionDTO sessionInfo, CompetenceCourseDTO paramPK, AsyncCallback<EditCompetenceCourseViewInitDataDTO> callback);

    void getDeleteCompetenceCourseViewInitData(SessionDTO sessionInfo, CompetenceCourseDTO paramPK, AsyncCallback<DeleteCompetenceCourseViewInitDataDTO> callback);

    void deleteCompetenceCourse(SessionDTO sessionInfo, CompetenceCourseDTO paramPK, AsyncCallback<Void> callback);

    void getDetailCompetenceCourseViewInitData(SessionDTO sessionInfo, CompetenceCourseDTO paramPK, AsyncCallback<DetailCompetenceCourseViewInitDataDTO> callback);

    void getSearchDegreeCriteriaViewInitData(SessionDTO sessionInfo, AsyncCallback<SearchDegreeCriteriaViewInitDataDTO> callback);

    void searchDegrees(SessionDTO sessionInfo, SearchDegreeCriteriaDTO param, AsyncCallback<SearchDegreeResultDTO> callback);

    void getCreateDegreeViewInitData(SessionDTO sessionInfo, AsyncCallback<CreateDegreeViewInitDataDTO> callback);

    void storeDegree(SessionDTO sessionInfo, DegreeDTO param, AsyncCallback<Void> callback);

    void getDeleteDegreeViewInitData(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<DeleteDegreeViewInitDataDTO> callback);

    void deleteDegree(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<Void> callback);

    void getDetailDegreeViewInitData(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<DetailDegreeViewInitDataDTO> callback);

    void getEditDegreeViewInitData(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<EditDegreeViewInitDataDTO> callback);

    void getDegreeCurricularPlans(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<DegreeDTO> callback);

    void getCreateDegreeCurricularPlanViewInitData(SessionDTO sessionInfo, DegreeDTO paramPK, AsyncCallback<CreateDegreeCurricularPlanViewInitDataDTO> callback);

    void storeDegreeCurricularPlan(SessionDTO sessionInfo, DegreeCurricularPlanDTO param, AsyncCallback<Void> callback);

    void getEditDegreeCurricularPlanViewInitData(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<EditDegreeCurricularPlanViewInitDataDTO> callback);

    void getDetailDegreeCurricularPlanViewInitData(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<DetailDegreeCurricularPlanViewInitDataDTO> callback);

    void getDeleteDegreeCurricularPlanViewInitData(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<DeleteDegreeCurricularPlanViewInitDataDTO> callback);

    void deleteDegreeCurricularPlan(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<Void> callback);

    void getCurricularCourses(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<DegreeCurricularPlanDTO> callback);

    void getCreateCurricularCourseViewInitData(SessionDTO sessionInfo, DegreeCurricularPlanDTO paramPK, AsyncCallback<CreateCurricularCourseViewInitDataDTO> callback);

    void storeCurricularCourse(SessionDTO sessionInfo, CurricularCourseDTO param, AsyncCallback<Void> callback);

    void getEditCurricularCourseViewInitData(SessionDTO sessionInfo, CurricularCourseDTO paramPK, AsyncCallback<EditCurricularCourseViewInitDataDTO> callback);

    void getDetailCurricularCourseViewInitData(SessionDTO sessionInfo, CurricularCourseDTO paramPK, AsyncCallback<DetailCurricularCourseViewInitDataDTO> callback);

    void getDeleteCurricularCourseViewInitData(SessionDTO sessionInfo, CurricularCourseDTO paramPK, AsyncCallback<DeleteCurricularCourseViewInitDataDTO> callback);

    void deleteCurricularCourse(SessionDTO sessionInfo, CurricularCourseDTO paramPK, AsyncCallback<Void> callback);

    void storeCompetenceCourseInformation(SessionDTO sessionInfo, CompetenceCourseInformationDTO param, AsyncCallback<Void> callback);

    void deleteCompetenceCourseInformation(SessionDTO sessionInfo, CompetenceCourseInformationDTO param, AsyncCallback<Void> callback);

    void getCompetenceCourseVersions(SessionDTO sessionInfo, CompetenceCourseDTO paramPK, AsyncCallback<CompetenceCourseDTO> callback);

    void getCompetenceCoursesForDepartment(SessionDTO sessionInfo, DepartmentDTO paramPK, AsyncCallback<DepartmentDTO> callback);
}
