package com.panemu.matapena.ui.form;

import com.panemu.matapena.core.pojo.VOBase;
import com.panemu.matapena.core.pojo.VOMember;
import com.panemu.matapena.ui.controller.CntlFrmMemberGrid;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.apache.log4j.Logger;
import org.openswing.swing.client.GridControl;
import org.openswing.swing.client.OptionPane;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author amrullah
 */
public class FrmMemberGrid extends InternalFrame {

    private CntlFrmMemberGrid controller;

    private static Logger logger = Logger.getLogger(FrmMemberGrid.class);

    /** Creates new form FrmMemberGrid */
    public FrmMemberGrid(CntlFrmMemberGrid controller) {
        this.setTitle("Daftar Anggota Matapena");
        this.controller = controller;
        initComponents();
        this.setUniqueInstance(true);
        prepareControls();
    }

    private void prepareControls() {
        grdMember.setValueObjectClassName(VOMember.class.getName());
        clmBirthPlace.setColumnName(VOMember.FieldName.birthPlace.name());
        clmMemberId.setColumnName(VOMember.FieldName.memberId.name());
        clmName.setColumnName(VOMember.FieldName.name.name());
        clmActivity.setColumnName(VOMember.FieldName.activity.name());
        clmBirthDate.setColumnName(VOMember.FieldName.birthDate.name());
        clmCreatedBy.setColumnName(VOBase.FieldName.createdBy.name());
        clmCreatedDate.setColumnName(VOBase.FieldName.createdDate.name());
        clmDomicileAddr.setColumnName(VOMember.FieldName.domAddr.name());
        clmEmail.setColumnName(VOMember.FieldName.email.name());
        clmGender.setColumnName(VOMember.FieldName.gender.name());
        clmHomeAddr.setColumnName(VOMember.FieldName.homeAddr.name());
        clmHomeCountry.setColumnName(VOMember.FieldName.homeCountry.name());
        clmHomeProvince.setColumnName(VOMember.FieldName.homeProv.name());
        clmID.setColumnName(VOBase.FieldName.id.name());
        clmModifiedBy.setColumnName(VOBase.FieldName.modifiedBy.name());
        clmModifiedDate.setColumnName(VOBase.FieldName.modifiedDate.name());
        clmPict.setColumnName(VOMember.FieldName.pict.name());
        clmPhone.setColumnName(VOMember.FieldName.phone.name());
        clmRayon.setColumnName(VOMember.FieldName.rayon.name());
        clmRegDate.setColumnName(VOMember.FieldName.regDate.name());
        clmSchool.setColumnName(VOMember.FieldName.school.name());
        clmVersion.setColumnName(VOBase.FieldName.version.name());
        clmWebsite.setColumnName(VOMember.FieldName.website.name());
        clmWorkpiece.setColumnName(VOMember.FieldName.workpiece.name());
        clmPict.setTextAlignment(SwingConstants.CENTER);
        clmGender.setTextAlignment(SwingConstants.CENTER);
        grdMember.setGridDataLocator(controller);
        grdMember.setController(controller);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        pnlButton = new javax.swing.JPanel();
        btnReload = new org.openswing.swing.client.ReloadButton();
        btnInsert = new org.openswing.swing.client.InsertButton();
        btnEdit = new org.openswing.swing.client.EditButton();
        btnSave = new org.openswing.swing.client.SaveButton();
        btnDelete = new org.openswing.swing.client.DeleteButton();
        btnCopy = new org.openswing.swing.client.CopyButton();
        btnExport = new org.openswing.swing.client.ExportButton();
        btnFilter = new org.openswing.swing.client.FilterButton();
        barNavigation = new org.openswing.swing.client.NavigatorBar();
        grdMember = new org.openswing.swing.client.GridControl();
        clmID = new org.openswing.swing.table.columns.client.IntegerColumn();
        clmMemberId = new org.openswing.swing.table.columns.client.TextColumn();
        clmPict = new org.openswing.swing.table.columns.client.ImageColumn();
        clmName = new org.openswing.swing.table.columns.client.TextColumn();
        clmGender = new org.openswing.swing.table.columns.client.ComboColumn();
        clmWorkpiece = new org.openswing.swing.table.columns.client.TextColumn();
        clmBirthPlace = new org.openswing.swing.table.columns.client.TextColumn();
        clmBirthDate = new org.openswing.swing.table.columns.client.DateColumn();
        clmRayon = new org.openswing.swing.table.columns.client.ComboColumn();
        clmActivity = new org.openswing.swing.table.columns.client.ComboColumn();
        clmRegDate = new org.openswing.swing.table.columns.client.DateColumn();
        clmPhone = new org.openswing.swing.table.columns.client.TextColumn();
        clmEmail = new org.openswing.swing.table.columns.client.TextColumn();
        clmWebsite = new org.openswing.swing.table.columns.client.TextColumn();
        clmDomicileAddr = new org.openswing.swing.table.columns.client.TextColumn();
        clmHomeAddr = new org.openswing.swing.table.columns.client.TextColumn();
        clmHomeProvince = new org.openswing.swing.table.columns.client.ComboColumn();
        clmHomeCountry = new org.openswing.swing.table.columns.client.ComboColumn();
        clmSchool = new org.openswing.swing.table.columns.client.TextColumn();
        clmModifiedBy = new org.openswing.swing.table.columns.client.TextColumn();
        clmModifiedDate = new org.openswing.swing.table.columns.client.DateTimeColumn();
        clmCreatedBy = new org.openswing.swing.table.columns.client.TextColumn();
        clmCreatedDate = new org.openswing.swing.table.columns.client.DateTimeColumn();
        clmVersion = new org.openswing.swing.table.columns.client.IntegerColumn();
        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnlButton.add(btnReload);
        pnlButton.add(btnInsert);
        pnlButton.add(btnEdit);
        pnlButton.add(btnSave);
        pnlButton.add(btnDelete);
        pnlButton.add(btnCopy);
        btnExport.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        pnlButton.add(btnExport);
        pnlButton.add(btnFilter);
        pnlButton.add(barNavigation);
        getContentPane().add(pnlButton, java.awt.BorderLayout.PAGE_START);
        grdMember.setCopyButton(btnCopy);
        grdMember.setDeleteButton(btnDelete);
        grdMember.setEditButton(btnEdit);
        grdMember.setFilterButton(btnFilter);
        grdMember.setFunctionId("FrmMemberGrid");
        grdMember.setInsertButton(btnInsert);
        grdMember.setNavBar(barNavigation);
        grdMember.setReloadButton(btnReload);
        grdMember.setRowHeight(90);
        grdMember.setSaveButton(btnSave);
        grdMember.setValueObjectClassName(VOMember.class.getName());
        grdMember.getColumnContainer().setLayout(new java.awt.GridLayout(1, 0));
        clmID.setColumnRequired(false);
        clmID.setColumnSortable(true);
        clmID.setPreferredWidth(50);
        clmID.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        grdMember.getColumnContainer().add(clmID);
        clmMemberId.setColumnFilterable(true);
        clmMemberId.setColumnName(VOMember.FieldName.memberId.toString());
        clmMemberId.setColumnSortable(true);
        clmMemberId.setEditableOnEdit(true);
        clmMemberId.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmMemberId);
        clmPict.setColumnRequired(false);
        clmPict.setEditableOnEdit(true);
        clmPict.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmPict);
        clmName.setColumnFilterable(true);
        clmName.setColumnSortable(true);
        clmName.setEditableOnEdit(true);
        clmName.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmName);
        clmGender.setColumnFilterable(true);
        clmGender.setColumnSortable(true);
        clmGender.setDomainId("GENDER");
        clmGender.setEditableOnEdit(true);
        clmGender.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmGender);
        clmWorkpiece.setColumnFilterable(true);
        clmWorkpiece.setColumnRequired(false);
        clmWorkpiece.setColumnSortable(true);
        clmWorkpiece.setEditableOnEdit(true);
        clmWorkpiece.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmWorkpiece);
        clmBirthPlace.setColumnFilterable(true);
        clmBirthPlace.setColumnRequired(false);
        clmBirthPlace.setColumnSortable(true);
        clmBirthPlace.setEditableOnEdit(true);
        clmBirthPlace.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmBirthPlace);
        clmBirthDate.setColumnFilterable(true);
        clmBirthDate.setColumnRequired(false);
        clmBirthDate.setColumnSortable(true);
        clmBirthDate.setEditableOnEdit(true);
        clmBirthDate.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmBirthDate);
        clmRayon.setColumnFilterable(true);
        clmRayon.setColumnRequired(false);
        clmRayon.setColumnSortable(true);
        clmRayon.setDomainId("RAYON");
        clmRayon.setEditableOnEdit(true);
        clmRayon.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmRayon);
        clmActivity.setColumnFilterable(true);
        clmActivity.setColumnSortable(true);
        clmActivity.setDomainId("ACTIVITY");
        clmActivity.setEditableOnEdit(true);
        clmActivity.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmActivity);
        clmRegDate.setColumnFilterable(true);
        clmRegDate.setColumnRequired(false);
        clmRegDate.setColumnSortable(true);
        clmRegDate.setEditableOnEdit(true);
        clmRegDate.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmRegDate);
        clmPhone.setColumnFilterable(true);
        clmPhone.setColumnRequired(false);
        clmPhone.setColumnSortable(true);
        clmPhone.setEditableOnEdit(true);
        clmPhone.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmPhone);
        clmEmail.setColumnFilterable(true);
        clmEmail.setColumnRequired(false);
        clmEmail.setColumnSortable(true);
        clmEmail.setEditableOnEdit(true);
        clmEmail.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmEmail);
        clmWebsite.setColumnFilterable(true);
        clmWebsite.setColumnRequired(false);
        clmWebsite.setColumnSortable(true);
        clmWebsite.setEditableOnEdit(true);
        clmWebsite.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmWebsite);
        clmDomicileAddr.setColumnFilterable(true);
        clmDomicileAddr.setColumnRequired(false);
        clmDomicileAddr.setColumnSortable(true);
        clmDomicileAddr.setEditableOnEdit(true);
        clmDomicileAddr.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmDomicileAddr);
        clmHomeAddr.setColumnFilterable(true);
        clmHomeAddr.setColumnRequired(false);
        clmHomeAddr.setColumnSortable(true);
        clmHomeAddr.setEditableOnEdit(true);
        clmHomeAddr.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmHomeAddr);
        clmHomeProvince.setColumnFilterable(true);
        clmHomeProvince.setColumnRequired(false);
        clmHomeProvince.setColumnSortable(true);
        clmHomeProvince.setDomainId("GENDER");
        clmHomeProvince.setEditableOnEdit(true);
        clmHomeProvince.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmHomeProvince);
        clmHomeCountry.setColumnFilterable(true);
        clmHomeCountry.setColumnRequired(false);
        clmHomeCountry.setColumnSortable(true);
        clmHomeCountry.setDomainId("GENDER");
        clmHomeCountry.setEditableOnEdit(true);
        clmHomeCountry.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmHomeCountry);
        clmSchool.setColumnFilterable(true);
        clmSchool.setColumnRequired(false);
        clmSchool.setColumnSortable(true);
        clmSchool.setEditableOnEdit(true);
        clmSchool.setEditableOnInsert(true);
        grdMember.getColumnContainer().add(clmSchool);
        clmModifiedBy.setColumnFilterable(true);
        clmModifiedBy.setColumnRequired(false);
        clmModifiedBy.setColumnSortable(true);
        grdMember.getColumnContainer().add(clmModifiedBy);
        clmModifiedDate.setColumnFilterable(true);
        clmModifiedDate.setColumnRequired(false);
        clmModifiedDate.setColumnSortable(true);
        grdMember.getColumnContainer().add(clmModifiedDate);
        clmCreatedBy.setColumnFilterable(true);
        clmCreatedBy.setColumnRequired(false);
        clmCreatedBy.setColumnSortable(true);
        grdMember.getColumnContainer().add(clmCreatedBy);
        clmCreatedDate.setColumnFilterable(true);
        clmCreatedDate.setColumnRequired(false);
        clmCreatedDate.setColumnSortable(true);
        grdMember.getColumnContainer().add(clmCreatedDate);
        clmVersion.setColumnFilterable(true);
        clmVersion.setColumnRequired(false);
        clmVersion.setColumnSortable(true);
        grdMember.getColumnContainer().add(clmVersion);
        getContentPane().add(grdMember, java.awt.BorderLayout.CENTER);
        pack();
    }

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            controller.export(grdMember.getTable().getVOListTableModel().getDataVector());
        } catch (Exception ex) {
            logger.error(ex.getMessage(), ex);
            OptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private org.openswing.swing.client.NavigatorBar barNavigation;

    private org.openswing.swing.client.CopyButton btnCopy;

    private org.openswing.swing.client.DeleteButton btnDelete;

    private org.openswing.swing.client.EditButton btnEdit;

    private org.openswing.swing.client.ExportButton btnExport;

    private org.openswing.swing.client.FilterButton btnFilter;

    private org.openswing.swing.client.InsertButton btnInsert;

    private org.openswing.swing.client.ReloadButton btnReload;

    private org.openswing.swing.client.SaveButton btnSave;

    private org.openswing.swing.table.columns.client.ComboColumn clmActivity;

    private org.openswing.swing.table.columns.client.DateColumn clmBirthDate;

    private org.openswing.swing.table.columns.client.TextColumn clmBirthPlace;

    private org.openswing.swing.table.columns.client.TextColumn clmCreatedBy;

    private org.openswing.swing.table.columns.client.DateTimeColumn clmCreatedDate;

    private org.openswing.swing.table.columns.client.TextColumn clmDomicileAddr;

    private org.openswing.swing.table.columns.client.TextColumn clmEmail;

    private org.openswing.swing.table.columns.client.ComboColumn clmGender;

    private org.openswing.swing.table.columns.client.TextColumn clmHomeAddr;

    private org.openswing.swing.table.columns.client.ComboColumn clmHomeCountry;

    private org.openswing.swing.table.columns.client.ComboColumn clmHomeProvince;

    private org.openswing.swing.table.columns.client.IntegerColumn clmID;

    private org.openswing.swing.table.columns.client.TextColumn clmMemberId;

    private org.openswing.swing.table.columns.client.TextColumn clmModifiedBy;

    private org.openswing.swing.table.columns.client.DateTimeColumn clmModifiedDate;

    private org.openswing.swing.table.columns.client.TextColumn clmName;

    private org.openswing.swing.table.columns.client.TextColumn clmPhone;

    private org.openswing.swing.table.columns.client.ImageColumn clmPict;

    private org.openswing.swing.table.columns.client.ComboColumn clmRayon;

    private org.openswing.swing.table.columns.client.DateColumn clmRegDate;

    private org.openswing.swing.table.columns.client.TextColumn clmSchool;

    private org.openswing.swing.table.columns.client.IntegerColumn clmVersion;

    private org.openswing.swing.table.columns.client.TextColumn clmWebsite;

    private org.openswing.swing.table.columns.client.TextColumn clmWorkpiece;

    private org.openswing.swing.client.GridControl grdMember;

    private javax.swing.JPanel pnlButton;

    public GridControl getGrid() {
        return grdMember;
    }
}
