package jumpingnotes.model.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MemberExperience generated by hbm2java
 */
@Entity
@Table(name = "member_experience", catalog = "jumping_notes")
public class MemberExperience implements java.io.Serializable {

    private Integer memberExpId;

    private Member member;

    private int platformExp;

    private int platformLevel;

    private int platformExpTotal;

    private String platformTrophy;

    private int jobExp;

    private int jobLevel;

    private int jobExpTotal;

    private String jobTrophy;

    public MemberExperience() {
    }

    public MemberExperience(Member member, int platformExp, int platformLevel, int platformExpTotal, int jobExp, int jobLevel, int jobExpTotal) {
        this.member = member;
        this.platformExp = platformExp;
        this.platformLevel = platformLevel;
        this.platformExpTotal = platformExpTotal;
        this.jobExp = jobExp;
        this.jobLevel = jobLevel;
        this.jobExpTotal = jobExpTotal;
    }

    public MemberExperience(Member member, int platformExp, int platformLevel, int platformExpTotal, String platformTrophy, int jobExp, int jobLevel, int jobExpTotal, String jobTrophy) {
        this.member = member;
        this.platformExp = platformExp;
        this.platformLevel = platformLevel;
        this.platformExpTotal = platformExpTotal;
        this.platformTrophy = platformTrophy;
        this.jobExp = jobExp;
        this.jobLevel = jobLevel;
        this.jobExpTotal = jobExpTotal;
        this.jobTrophy = jobTrophy;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "member_exp_id", unique = true, nullable = false)
    public Integer getMemberExpId() {
        return this.memberExpId;
    }

    public void setMemberExpId(Integer memberExpId) {
        this.memberExpId = memberExpId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    @Column(name = "platform_exp", nullable = false)
    public int getPlatformExp() {
        return this.platformExp;
    }

    public void setPlatformExp(int platformExp) {
        this.platformExp = platformExp;
    }

    @Column(name = "platform_level", nullable = false)
    public int getPlatformLevel() {
        return this.platformLevel;
    }

    public void setPlatformLevel(int platformLevel) {
        this.platformLevel = platformLevel;
    }

    @Column(name = "platform_exp_total", nullable = false)
    public int getPlatformExpTotal() {
        return this.platformExpTotal;
    }

    public void setPlatformExpTotal(int platformExpTotal) {
        this.platformExpTotal = platformExpTotal;
    }

    @Column(name = "platform_trophy", length = 100)
    public String getPlatformTrophy() {
        return this.platformTrophy;
    }

    public void setPlatformTrophy(String platformTrophy) {
        this.platformTrophy = platformTrophy;
    }

    @Column(name = "job_exp", nullable = false)
    public int getJobExp() {
        return this.jobExp;
    }

    public void setJobExp(int jobExp) {
        this.jobExp = jobExp;
    }

    @Column(name = "job_level", nullable = false)
    public int getJobLevel() {
        return this.jobLevel;
    }

    public void setJobLevel(int jobLevel) {
        this.jobLevel = jobLevel;
    }

    @Column(name = "job_exp_total", nullable = false)
    public int getJobExpTotal() {
        return this.jobExpTotal;
    }

    public void setJobExpTotal(int jobExpTotal) {
        this.jobExpTotal = jobExpTotal;
    }

    @Column(name = "job_trophy", length = 100)
    public String getJobTrophy() {
        return this.jobTrophy;
    }

    public void setJobTrophy(String jobTrophy) {
        this.jobTrophy = jobTrophy;
    }
}
