package uk.ac.ebi.intact.plugin.psigenerator;

import org.apache.maven.plugin.MojoExecutionException;
import org.codehaus.plexus.util.FileUtils;
import java.io.IOException;

/**
 * Deletes the files generated by the plugin
 *
 * @author Bruno Aranda (baranda@ebi.ac.uk)
 * @version $Id: PsiXmlGeneratorCleanMojo.java 5772 2006-08-11 15:08:37Z baranda $
 * @since <pre>04/08/2006</pre>
 *
 * @goal clean
 */
public class PsiXmlGeneratorCleanMojo extends PsiXmlGeneratorAbstractMojo {

    public void execute() throws MojoExecutionException {
        if (targetPath.exists()) {
            try {
                FileUtils.deleteDirectory(targetPath);
            } catch (IOException e) {
                throw new MojoExecutionException("Problem deleting folder: " + targetPath);
            }
        }
    }
}
