package fr.uparis10.miage.annoarius.edit.vue.frame;

import java.awt.BorderLayout;
import javax.swing.Icon;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import fr.uparis10.miage.annoarius.edit.vue.interfaces.*;
import fr.uparis10.miage.annoarius.edit.utilitaires.UtilitaireClient;

/**
 *
 * @author siby002
 */
public class IntFrameCRUD_app extends javax.swing.JInternalFrame implements IIntFrame {

    private IFramePrincipale contenant;

    private IPanelCRUD panelCRUD;

    /** Creates new form IntFramePersonnelMedicalCRUD */
    public IntFrameCRUD_app() {
        initComponents();
    }

    public IntFrameCRUD_app(IPanelCRUD panelCRUD) {
        this();
        this.panelCRUD = panelCRUD;
        this.panelCRUD.setContenant(this);
        this.panelPrincipal.add((JPanel) panelCRUD, BorderLayout.CENTER);
        activerBoutons();
        setTitle(" Ouvrir...");
    }

    public IFramePrincipale getContenant() {
        return contenant;
    }

    public void setContenant(IFramePrincipale contenant) {
        mnuItemFenetre.setText("Gestion Des Ressources ");
        contenant.ajouterSupprimerFenetreMenuItem(true, mnuItemFenetre);
        this.contenant = contenant;
    }

    public void ajouterMenuItem(JMenuItem menuItem) {
        mnuAction.add(menuItem);
    }

    public String getTitre() {
        return panelCRUD.getTypeObject().getTitre();
    }

    public Icon getIconObject() {
        return panelCRUD.getTypeObject().getIconObject();
    }

    private void activerBoutons() {
        mnuItemRecherche.setEnabled(panelCRUD.activerRecherche());
        btnRechercher.setEnabled(panelCRUD.activerRechercher());
        mnuItemRechercher.setEnabled(panelCRUD.activerRechercher());
        mnuItemModifier.setEnabled(panelCRUD.activerModifier());
        btnSupprimer.setEnabled(panelCRUD.activerSupprimer());
        mnuItemSupprimer.setEnabled(panelCRUD.activerSupprimer());
    }

    public boolean fermer() {
        if (!panelCRUD.fermer()) {
            return false;
        }
        contenant.ajouterSupprimerFenetreMenuItem(false, mnuItemFenetre);
        dispose();
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        mnuItemFenetre = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnRechercher = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnFermer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAction = new javax.swing.JMenu();
        mnuItemRecherche = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuItemRechercher = new javax.swing.JMenuItem();
        mnuItemModifier = new javax.swing.JMenuItem();
        mnuItemSupprimer = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnuItemFermer = new javax.swing.JMenuItem();
        mnuItemFenetre.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemFenetre.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFenetreActionPerformed(evt);
            }
        });
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(450, 500));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jPanel1.setPreferredSize(new java.awt.Dimension(455, 10));
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 590, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10, Short.MAX_VALUE));
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        jPanel2.setPreferredSize(new java.awt.Dimension(455, 60));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));
        jPanel6.setBackground(new java.awt.Color(230, 230, 230));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel6.setPreferredSize(new java.awt.Dimension(480, 40));
        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));
        jPanel5.setBackground(new java.awt.Color(230, 230, 230));
        btnRechercher.setFont(new java.awt.Font("Arial", 0, 12));
        btnRechercher.setText("Ouvrir");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });
        btnSupprimer.setFont(new java.awt.Font("Arial", 0, 12));
        btnSupprimer.setText("Annuler");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 293, Short.MAX_VALUE).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(btnRechercher).addGap(153, 153, 153).addComponent(btnSupprimer).addGap(0, 0, Short.MAX_VALUE))));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 28, Short.MAX_VALUE).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGap(0, 2, Short.MAX_VALUE).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnRechercher).addComponent(btnSupprimer)).addGap(0, 3, Short.MAX_VALUE))));
        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);
        jPanel7.setBackground(new java.awt.Color(230, 230, 230));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 28));
        btnFermer.setFont(new java.awt.Font("Arial", 0, 12));
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100, Short.MAX_VALUE).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGap(0, 13, Short.MAX_VALUE).addComponent(btnFermer).addGap(0, 14, Short.MAX_VALUE))));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 28, Short.MAX_VALUE).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGap(0, 2, Short.MAX_VALUE).addComponent(btnFermer).addGap(0, 3, Short.MAX_VALUE))));
        jPanel6.add(jPanel7, java.awt.BorderLayout.EAST);
        jPanel2.add(jPanel6);
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 199));
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 20, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 348, Short.MAX_VALUE));
        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 199));
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 20, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 348, Short.MAX_VALUE));
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);
        panelPrincipal.setBackground(new java.awt.Color(230, 230, 230));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        panelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);
        mnuAction.setText("Action");
        mnuAction.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemRecherche.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemRecherche.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemRecherche.setText("Recherche");
        mnuItemRecherche.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRechercheActionPerformed(evt);
            }
        });
        mnuAction.add(mnuItemRecherche);
        mnuAction.add(jSeparator1);
        mnuItemRechercher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemRechercher.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemRechercher.setText("Rechercher");
        mnuItemRechercher.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRechercherActionPerformed(evt);
            }
        });
        mnuAction.add(mnuItemRechercher);
        mnuItemModifier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemModifier.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemModifier.setText("Modifier");
        mnuItemModifier.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemModifierActionPerformed(evt);
            }
        });
        mnuAction.add(mnuItemModifier);
        mnuItemSupprimer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemSupprimer.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemSupprimer.setText("Supprimer");
        mnuItemSupprimer.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSupprimerActionPerformed(evt);
            }
        });
        mnuAction.add(mnuItemSupprimer);
        mnuAction.add(jSeparator2);
        mnuItemFermer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemFermer.setFont(new java.awt.Font("Arial", 0, 12));
        mnuItemFermer.setText("Fermer");
        mnuItemFermer.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFermerActionPerformed(evt);
            }
        });
        mnuAction.add(mnuItemFermer);
        jMenuBar1.add(mnuAction);
        setJMenuBar(jMenuBar1);
        pack();
    }

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
        fermer();
    }

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.rechercher();
        activerBoutons();
    }

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.supprimer();
        activerBoutons();
    }

    private void mnuItemRechercherActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.rechercher();
        activerBoutons();
    }

    private void mnuItemModifierActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.modifier();
        activerBoutons();
    }

    private void mnuItemSupprimerActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.supprimer();
        activerBoutons();
    }

    private void mnuItemRechercheActionPerformed(java.awt.event.ActionEvent evt) {
        panelCRUD.recherche();
        activerBoutons();
    }

    private void mnuItemFenetreActionPerformed(java.awt.event.ActionEvent evt) {
        UtilitaireClient.montrer(this);
    }

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {
        fermer();
    }

    private void mnuItemFermerActionPerformed(java.awt.event.ActionEvent evt) {
        fermer();
    }

    private javax.swing.JButton btnFermer;

    private javax.swing.JButton btnRechercher;

    private javax.swing.JButton btnSupprimer;

    private javax.swing.JMenuBar jMenuBar1;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JSeparator jSeparator1;

    private javax.swing.JSeparator jSeparator2;

    private javax.swing.JMenu mnuAction;

    private javax.swing.JMenuItem mnuItemFenetre;

    private javax.swing.JMenuItem mnuItemFermer;

    private javax.swing.JMenuItem mnuItemModifier;

    private javax.swing.JMenuItem mnuItemRecherche;

    private javax.swing.JMenuItem mnuItemRechercher;

    private javax.swing.JMenuItem mnuItemSupprimer;

    private javax.swing.JPanel panelPrincipal;
}
