package org.domain.analyticalcrm.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TelephoneType generated by hbm2java
 */
@Entity
@Table(name = "telephone_type", schema = "public")
public class TelephoneType implements java.io.Serializable {

    private int idTelephoneType;

    private String telephoneTypeValue;

    private Set<Telephone> telephones = new HashSet<Telephone>(0);

    public TelephoneType() {
    }

    public TelephoneType(int idTelephoneType) {
        this.idTelephoneType = idTelephoneType;
    }

    public TelephoneType(int idTelephoneType, String telephoneTypeValue, Set<Telephone> telephones) {
        this.idTelephoneType = idTelephoneType;
        this.telephoneTypeValue = telephoneTypeValue;
        this.telephones = telephones;
    }

    @Id
    @Column(name = "id_telephone_type", unique = true, nullable = false)
    @NotNull
    public int getIdTelephoneType() {
        return this.idTelephoneType;
    }

    public void setIdTelephoneType(int idTelephoneType) {
        this.idTelephoneType = idTelephoneType;
    }

    @Column(name = "telephone_type_value", length = 8)
    @Length(max = 8)
    public String getTelephoneTypeValue() {
        return this.telephoneTypeValue;
    }

    public void setTelephoneTypeValue(String telephoneTypeValue) {
        this.telephoneTypeValue = telephoneTypeValue;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "telephoneType")
    public Set<Telephone> getTelephones() {
        return this.telephones;
    }

    public void setTelephones(Set<Telephone> telephones) {
        this.telephones = telephones;
    }
}
