package com.kongur.star.venus.manager.courses;

import java.util.List;
import com.kongur.star.venus.common.page.Paginable;
import com.kongur.star.venus.domain.courses.TeachingMembersDO;

public interface TeachingMembersManager {

    /***
	 * Auto generated insertTeachingMembers method by Codegen.
	 * @param teachingMembersDO Auto generated by Codegen.
	 */
    Long insertTeachingMembers(TeachingMembersDO teachingMembersDO);

    /***
	 * Auto generated updateTeachingMembers method by Codegen.
	 * @param teachingMembersDO Auto generated by Codegen.
	 */
    Integer updateTeachingMembers(TeachingMembersDO teachingMembersDO);

    /***
	 * Auto generated selectTeachingMembersById method by Codegen.
	 * @param id Auto generated by Codegen.
	 */
    TeachingMembersDO selectTeachingMembersById(Long id);

    /***
	 * Auto generated selectTeachingMembersForPagin method by Codegen.
	 * @param teachingMembersDO Auto generated by Codegen.
	 * @param qTotalCount Auto generated by Codegen.
	 * @param qPagination Auto generated by Codegen.
	 */
    Paginable<TeachingMembersDO> selectTeachingMembersForPagin(TeachingMembersDO teachingMembersDO, String qTotalCount, String qPagination);

    /**
	 * ɾ���ʦ��Ա
	 * @param tId
	 */
    void deleteTeachingMember(Long tId);

    /**
	 * ��ݿγ�ID��ý̳̳�Ա�б�
	 * @param cId
	 * @return
	 */
    List<TeachingMembersDO> getTeachersByCourseId(Long cId);

    List<TeachingMembersDO> getMajorTeacherByCourseId(Long cId);

    /**
	 * ��ݿγ�ID��ÿγ̸����˶���
	 * @param cId
	 * @return
	 */
    TeachingMembersDO getChargeTeacherByCourseId(Long cId);
}
