package br.ufal.ic.forbile.infra.emathema.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/emathema.owl#THINGCSCL
 *
 * @version generated on Wed Sep 27 02:26:48 GMT-03:00 2006
 */
public interface THINGCSCL extends OWLIndividual {
}
