package com.panemu.trensoft.obligation.ui.form;

import com.panemu.trensoft.core.pojo.VOBase;
import com.panemu.trensoft.obligation.pojo.Obligation;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.table.java.GridDataLocator;
import org.openswing.swing.util.client.ClientSettings;
import com.panemu.trensoft.obligation.ui.controller.CntlFrmObligation;

/**
 *
 * @author amrullah
 */
public class FrmObligation extends InternalFrame {

    private CntlFrmObligation controller;

    /** Creates new form BeanForm */
    public FrmObligation(CntlFrmObligation ogc) {
        try {
            this.controller = ogc;
            initComponents();
            prepareControls(ogc);
            clmCalendar.setDomainId("CALENDAR");
            this.setSize(750, 330);
            setTitle(ClientSettings.getInstance().getResources().getResource("Obligation Templates"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void prepareControls(CntlFrmObligation cntl) {
        clmCalendar.setColumnName(Obligation.FieldName.calendar.toString());
        clmCreatedDate.setColumnName(VOBase.FieldName.createdDate.toString());
        clmDescription.setColumnName(Obligation.FieldName.description.toString());
        clmDueDate.setColumnName(Obligation.FieldName.dueDate.toString());
        clmEndDate.setColumnName(Obligation.FieldName.endDate.toString());
        clmId.setColumnName(VOBase.FieldName.id.toString());
        clmModifiedBy.setColumnName(VOBase.FieldName.modifiedBy.toString());
        clmModifiedDate.setColumnName(VOBase.FieldName.modifiedDate.toString());
        clmPerPayment.setColumnName(Obligation.FieldName.perPayment.toString());
        clmProrate.setColumnName(Obligation.FieldName.prorate.toString());
        clmStartDate.setColumnName(Obligation.FieldName.startDate.toString());
        clmTotalPayment.setColumnName(Obligation.FieldName.totalPayment.toString());
        clmVersion.setColumnName(VOBase.FieldName.version.toString());
        grdObligation.setController(controller);
        grdObligation.setGridDataLocator(controller);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        grdObligation = new org.openswing.swing.client.GridControl();
        clmId = new org.openswing.swing.table.columns.client.IntegerColumn();
        clmDescription = new org.openswing.swing.table.columns.client.TextColumn();
        clmCalendar = new org.openswing.swing.table.columns.client.ComboColumn();
        clmProrate = new org.openswing.swing.table.columns.client.CheckBoxColumn();
        clmStartDate = new org.openswing.swing.table.columns.client.DateColumn();
        clmEndDate = new org.openswing.swing.table.columns.client.DateColumn();
        clmDueDate = new org.openswing.swing.table.columns.client.DateColumn();
        clmPerPayment = new org.openswing.swing.table.columns.client.IntegerColumn();
        clmTotalPayment = new org.openswing.swing.table.columns.client.IntegerColumn();
        clmCreatedDate = new org.openswing.swing.table.columns.client.DateTimeColumn();
        clmModifiedDate = new org.openswing.swing.table.columns.client.DateTimeColumn();
        clmModifiedBy = new org.openswing.swing.table.columns.client.TextColumn();
        clmVersion = new org.openswing.swing.table.columns.client.IntegerColumn();
        topPanel = new javax.swing.JPanel();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        exportButton1 = new org.openswing.swing.client.ExportButton();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        grdObligation.setDeleteButton(deleteButton1);
        grdObligation.setEditButton(editButton1);
        grdObligation.setExportButton(exportButton1);
        grdObligation.setFilterButton(filterButton1);
        grdObligation.setInsertButton(insertButton1);
        grdObligation.setInsertRowsOnTop(false);
        grdObligation.setMaxNumberOfRowsOnInsert(5);
        grdObligation.setNavBar(navigatorBar1);
        grdObligation.setReloadButton(reloadButton1);
        grdObligation.setSaveButton(saveButton1);
        grdObligation.setSingleExpandableRow(true);
        grdObligation.setValueObjectClassName(Obligation.class.getName());
        grdObligation.getColumnContainer().setLayout(new java.awt.GridLayout(1, 0));
        clmId.setColumnRequired(false);
        clmId.setColumnSortable(true);
        grdObligation.getColumnContainer().add(clmId);
        clmDescription.setColumnSortable(true);
        clmDescription.setEditableOnEdit(true);
        clmDescription.setEditableOnInsert(true);
        clmDescription.setHeaderColumnName("oblDesc");
        grdObligation.getColumnContainer().add(clmDescription);
        clmCalendar.setColumnFilterable(true);
        clmCalendar.setColumnSortable(true);
        clmCalendar.setEditableOnEdit(true);
        clmCalendar.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmCalendar);
        clmProrate.setEditableOnEdit(true);
        clmProrate.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmProrate);
        clmStartDate.setEditableOnEdit(true);
        clmStartDate.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmStartDate);
        clmEndDate.setEditableOnEdit(true);
        clmEndDate.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmEndDate);
        clmDueDate.setColumnRequired(false);
        clmDueDate.setEditableOnEdit(true);
        clmDueDate.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmDueDate);
        clmPerPayment.setColumnFilterable(true);
        clmPerPayment.setColumnSortable(true);
        clmPerPayment.setEditableOnEdit(true);
        clmPerPayment.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmPerPayment);
        clmTotalPayment.setColumnFilterable(true);
        clmTotalPayment.setColumnSortable(true);
        clmTotalPayment.setEditableOnEdit(true);
        clmTotalPayment.setEditableOnInsert(true);
        grdObligation.getColumnContainer().add(clmTotalPayment);
        clmCreatedDate.setColumnRequired(false);
        clmCreatedDate.setColumnSortable(true);
        grdObligation.getColumnContainer().add(clmCreatedDate);
        clmModifiedDate.setColumnRequired(false);
        clmModifiedDate.setColumnSortable(true);
        grdObligation.getColumnContainer().add(clmModifiedDate);
        clmModifiedBy.setColumnRequired(false);
        clmModifiedBy.setColumnSortable(true);
        grdObligation.getColumnContainer().add(clmModifiedBy);
        clmVersion.setColumnRequired(false);
        grdObligation.getColumnContainer().add(clmVersion);
        getContentPane().add(grdObligation, java.awt.BorderLayout.CENTER);
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        topPanel.add(reloadButton1);
        topPanel.add(insertButton1);
        topPanel.add(editButton1);
        topPanel.add(saveButton1);
        topPanel.add(deleteButton1);
        topPanel.add(exportButton1);
        topPanel.add(filterButton1);
        topPanel.add(navigatorBar1);
        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);
    }

    private org.openswing.swing.table.columns.client.ComboColumn clmCalendar;

    private org.openswing.swing.table.columns.client.DateTimeColumn clmCreatedDate;

    private org.openswing.swing.table.columns.client.TextColumn clmDescription;

    private org.openswing.swing.table.columns.client.DateColumn clmDueDate;

    private org.openswing.swing.table.columns.client.DateColumn clmEndDate;

    private org.openswing.swing.table.columns.client.IntegerColumn clmId;

    private org.openswing.swing.table.columns.client.TextColumn clmModifiedBy;

    private org.openswing.swing.table.columns.client.DateTimeColumn clmModifiedDate;

    private org.openswing.swing.table.columns.client.IntegerColumn clmPerPayment;

    private org.openswing.swing.table.columns.client.CheckBoxColumn clmProrate;

    private org.openswing.swing.table.columns.client.DateColumn clmStartDate;

    private org.openswing.swing.table.columns.client.IntegerColumn clmTotalPayment;

    private org.openswing.swing.table.columns.client.IntegerColumn clmVersion;

    private org.openswing.swing.client.DeleteButton deleteButton1;

    private org.openswing.swing.client.EditButton editButton1;

    private org.openswing.swing.client.ExportButton exportButton1;

    private org.openswing.swing.client.FilterButton filterButton1;

    private org.openswing.swing.client.GridControl grdObligation;

    private org.openswing.swing.client.InsertButton insertButton1;

    private org.openswing.swing.client.NavigatorBar navigatorBar1;

    private org.openswing.swing.client.ReloadButton reloadButton1;

    private org.openswing.swing.client.SaveButton saveButton1;

    private javax.swing.JPanel topPanel;
}
