package com.tetratech.edas2.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.hibernate.validator.Length;

/**
 * Citation generated by hbm2java
 */
@Entity
@Table(name = "ED_CITATION")
public class Citation extends AttributableUpdateRetireEntity implements java.io.Serializable {

    private Long uid;

    private Organization organization;

    private String id;

    private String creator;

    private Date date;

    private String publisher;

    private String subject;

    private String title;

    private String description;

    private Boolean epaOriginalValue;

    private Set<ResultTaxonFeedingGroup> resultTaxonFeedingGroups = new HashSet<ResultTaxonFeedingGroup>(0);

    private Set<ResultTaxonHabit> resultTaxonHabits = new HashSet<ResultTaxonHabit>(0);

    private Set<ResultTaxonDetail> resultTaxonDetails = new HashSet<ResultTaxonDetail>(0);

    public Citation() {
    }

    public Citation(Long uid, Organization organization, String id, Date date, String title) {
        this.uid = uid;
        this.organization = organization;
        this.id = id;
        this.date = date;
        this.title = title;
    }

    public Citation(Long uid, Organization organization, String id, String creator, Date date, String publisher, String subject, String title, String description, Boolean epaOriginalValue, Set<ResultTaxonFeedingGroup> resultTaxonFeedingGroups, Set<ResultTaxonHabit> resultTaxonHabits, Set<ResultTaxonDetail> resultTaxonDetails) {
        this.uid = uid;
        this.organization = organization;
        this.id = id;
        this.creator = creator;
        this.date = date;
        this.publisher = publisher;
        this.subject = subject;
        this.title = title;
        this.description = description;
        this.epaOriginalValue = epaOriginalValue;
        this.resultTaxonFeedingGroups = resultTaxonFeedingGroups;
        this.resultTaxonHabits = resultTaxonHabits;
        this.resultTaxonDetails = resultTaxonDetails;
    }

    @Id
    @Column(name = "CITATN_UID", unique = true, nullable = false, precision = 6, scale = 0)
    public Long getUid() {
        return this.uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORG_UID", nullable = false)
    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    @Column(name = "CITATN_ID", nullable = false)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "CITATN_CREATOR", length = 120)
    @Length(max = 120)
    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CITATN_DATE", nullable = false, length = 7)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "CITATN_PUBLISHER", length = 60)
    @Length(max = 60)
    public String getPublisher() {
        return this.publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    @Column(name = "CITATN_SUBJECT", length = 500)
    @Length(max = 500)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "CITATN_TITLE", nullable = false, length = 120)
    @Length(max = 120)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "CITATN_DESCR", length = 300)
    @Length(max = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "EPA_ORIG_FLAG", length = 1)
    @Type(type = "yes_no")
    public Boolean getEpaOriginalValue() {
        return this.epaOriginalValue;
    }

    public void setEpaOriginalValue(Boolean epaOriginalValue) {
        this.epaOriginalValue = epaOriginalValue;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "citation")
    public Set<ResultTaxonFeedingGroup> getResultTaxonFeedingGroups() {
        return this.resultTaxonFeedingGroups;
    }

    public void setResultTaxonFeedingGroups(Set<ResultTaxonFeedingGroup> resultTaxonFeedingGroups) {
        this.resultTaxonFeedingGroups = resultTaxonFeedingGroups;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "citation")
    public Set<ResultTaxonHabit> getResultTaxonHabits() {
        return this.resultTaxonHabits;
    }

    public void setResultTaxonHabits(Set<ResultTaxonHabit> resultTaxonHabits) {
        this.resultTaxonHabits = resultTaxonHabits;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "citation")
    public Set<ResultTaxonDetail> getResultTaxonDetails() {
        return this.resultTaxonDetails;
    }

    public void setResultTaxonDetails(Set<ResultTaxonDetail> resultTaxonDetails) {
        this.resultTaxonDetails = resultTaxonDetails;
    }
}
