package org.mjrdevelopment.istoreit.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;

/**
 * MetadataProperty generated by hbm2java
 */
@Entity
@Indexed
@Table(name = "METADATA_PROPERTY", catalog = "ISTOREIT")
@XmlRootElement(name = "MetadataProperty", namespace = "http://mjrdevelopment.org/iStoreIT")
@JsonIgnoreProperties({ "metadataPropertyType", "entityModel" })
public class MetadataProperty extends EntityBase implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 4080798887127503024L;

    private String id;

    private MetadataPropertyType metadataPropertyType;

    private EntityModel entityModel;

    private String key;

    private String value;

    private String metadataPropertyTypeId;

    private String entityModelId;

    public MetadataProperty() {
    }

    public MetadataProperty(String id, MetadataPropertyType metadataPropertyType, EntityModel entityModel, String key) {
        this.id = id;
        this.metadataPropertyType = metadataPropertyType;
        this.entityModel = entityModel;
        this.key = key;
    }

    public MetadataProperty(String id, String metadataPropertyTypeId, EntityModel entityModel, String key, String value) {
        this.id = id;
        this.setMetadataPropertyTypeId(metadataPropertyTypeId);
        this.entityModel = entityModel;
        this.key = key;
        this.value = value;
    }

    @Id
    @DocumentId
    @Column(name = "ID", unique = true, nullable = false, length = 38)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ContainedIn
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ENTITY_ID", nullable = false)
    @XmlTransient
    public EntityModel getEntityModel() {
        return this.entityModel;
    }

    public void setEntityModel(EntityModel entityModel) {
        this.entityModel = entityModel;
    }

    @Field(index = Index.UN_TOKENIZED)
    @Column(name = "ENTITY_ID", unique = false, nullable = false, insertable = false, updatable = false, length = 38)
    public String getEntityModelId() {
        return entityModelId;
    }

    public void setEntityModelId(String entityModelId) {
        this.entityModelId = entityModelId;
    }

    @Field(index = Index.UN_TOKENIZED)
    @Column(name = "METADATA_KEY", nullable = false, length = 255)
    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @Field(index = Index.TOKENIZED)
    @Column(name = "METADATA_VALUE", length = 2048)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @IndexedEmbedded
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TYPE_ID", nullable = false)
    @XmlTransient
    public MetadataPropertyType getMetadataPropertyType() {
        return this.metadataPropertyType;
    }

    public void setMetadataPropertyType(MetadataPropertyType metadataPropertyType) {
        this.metadataPropertyType = metadataPropertyType;
    }

    @Field(index = Index.UN_TOKENIZED)
    @Column(name = "TYPE_ID", unique = false, nullable = false, insertable = false, updatable = false, length = 45)
    public String getMetadataPropertyTypeId() {
        return metadataPropertyTypeId;
    }

    public void setMetadataPropertyTypeId(String metadataPropertyTypeId) {
        this.metadataPropertyTypeId = metadataPropertyTypeId;
    }
}
