package MB_Models.NetVirus_Exp.JavaModels.GeneratedModelsDEVS_Suite;

import java.awt.*;
import java.io.*;
import java.util.*;
import DevsSuite.GenCol.*;
import DevsSuite.model.modeling.*;
import DevsSuite.model.simulation.*;
import DevsSuite.view.modeling.*;
import DevsSuite.view.simView.*;

public class RouterVirus_1_1 extends ViewableDigraph {

    public RouterVirus_1_1() {
        this("RouterVirus_1_1");
    }

    public RouterVirus_1_1(String name) {
        super(name);
        addInport("alertSignal");
        addInport("in");
        addOutport("out");
        addOutport("virusDet");
        ViewableAtomic RouterQ_1_0 = new RouterQ_0_0();
        ViewableAtomic VirusProcQ_1_0 = new VirusProcQ_0_0();
        add(RouterQ_1_0);
        add(VirusProcQ_1_0);
        addCoupling(RouterQ_1_0, "outVirus", VirusProcQ_1_0, "inVirus");
        addCoupling(this, "alertSignal", RouterQ_1_0, "alertSignal");
        addCoupling(this, "in", RouterQ_1_0, "in");
        addCoupling(RouterQ_1_0, "out", this, "out");
        addCoupling(VirusProcQ_1_0, "virusDet", this, "virusDet");
        addCoupling(VirusProcQ_1_0, "out", RouterQ_1_0, "in");
        initialize();
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView() {
        preferredSize = new Dimension(384, 137);
        ((ViewableComponent) withName("RouterQ_0_0")).setPreferredLocation(new Point(-8, 24));
        ((ViewableComponent) withName("VirusProcQ_0_0")).setPreferredLocation(new Point(-5, 81));
    }
}
