package com.iclotho.eshop.web.base.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import com.iclotho.eshop.web.BaseVO;

public class OrderVO implements Serializable {

    private int page;

    private String startDate;

    private String endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.ORDER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private Long orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.MERCHANT_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String merchantId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.ORDER_AMT
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private BigDecimal orderAmt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.SHIPPING_FEE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private BigDecimal shippingFee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.CURRENCY_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String currencyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.RECEIVER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String receiverId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.order_addr_id
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private Long orderAddrId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.ORDER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String orderDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.AVAILABLE_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String availableDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.DELIVER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String deliverDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.DELIVER_USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String deliverUserId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.RECEIPT_NO
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String receiptNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.ORDER_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private Integer orderStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.TRANS_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private Integer transStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_order.MERCHANT_OPERATORID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private String merchantOperatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_order
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.ORDER_ID
     *
     * @return the value of t_order.ORDER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.ORDER_ID
     *
     * @param orderId the value for t_order.ORDER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.USER_ID
     *
     * @return the value of t_order.USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.USER_ID
     *
     * @param userId the value for t_order.USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.MERCHANT_ID
     *
     * @return the value of t_order.MERCHANT_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.MERCHANT_ID
     *
     * @param merchantId the value for t_order.MERCHANT_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.ORDER_AMT
     *
     * @return the value of t_order.ORDER_AMT
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public BigDecimal getOrderAmt() {
        return orderAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.ORDER_AMT
     *
     * @param orderAmt the value for t_order.ORDER_AMT
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setOrderAmt(BigDecimal orderAmt) {
        this.orderAmt = orderAmt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.SHIPPING_FEE
     *
     * @return the value of t_order.SHIPPING_FEE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.SHIPPING_FEE
     *
     * @param shippingFee the value for t_order.SHIPPING_FEE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.CURRENCY_ID
     *
     * @return the value of t_order.CURRENCY_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.CURRENCY_ID
     *
     * @param currencyId the value for t_order.CURRENCY_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setCurrencyId(String currencyId) {
        this.currencyId = currencyId == null ? null : currencyId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.RECEIVER_ID
     *
     * @return the value of t_order.RECEIVER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.RECEIVER_ID
     *
     * @param receiverId the value for t_order.RECEIVER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.order_addr_id
     *
     * @return the value of t_order.order_addr_id
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public Long getOrderAddrId() {
        return orderAddrId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.order_addr_id
     *
     * @param orderAddrId the value for t_order.order_addr_id
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setOrderAddrId(Long orderAddrId) {
        this.orderAddrId = orderAddrId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.ORDER_DATE
     *
     * @return the value of t_order.ORDER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.ORDER_DATE
     *
     * @param orderDate the value for t_order.ORDER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate == null ? null : orderDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.AVAILABLE_DATE
     *
     * @return the value of t_order.AVAILABLE_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getAvailableDate() {
        return availableDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.AVAILABLE_DATE
     *
     * @param availableDate the value for t_order.AVAILABLE_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setAvailableDate(String availableDate) {
        this.availableDate = availableDate == null ? null : availableDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.DELIVER_DATE
     *
     * @return the value of t_order.DELIVER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getDeliverDate() {
        return deliverDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.DELIVER_DATE
     *
     * @param deliverDate the value for t_order.DELIVER_DATE
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setDeliverDate(String deliverDate) {
        this.deliverDate = deliverDate == null ? null : deliverDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.DELIVER_USER_ID
     *
     * @return the value of t_order.DELIVER_USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getDeliverUserId() {
        return deliverUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.DELIVER_USER_ID
     *
     * @param deliverUserId the value for t_order.DELIVER_USER_ID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setDeliverUserId(String deliverUserId) {
        this.deliverUserId = deliverUserId == null ? null : deliverUserId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.RECEIPT_NO
     *
     * @return the value of t_order.RECEIPT_NO
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getReceiptNo() {
        return receiptNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.RECEIPT_NO
     *
     * @param receiptNo the value for t_order.RECEIPT_NO
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo == null ? null : receiptNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.ORDER_STATUS
     *
     * @return the value of t_order.ORDER_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.ORDER_STATUS
     *
     * @param orderStatus the value for t_order.ORDER_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.TRANS_STATUS
     *
     * @return the value of t_order.TRANS_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public Integer getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.TRANS_STATUS
     *
     * @param transStatus the value for t_order.TRANS_STATUS
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setTransStatus(Integer transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_order.MERCHANT_OPERATORID
     *
     * @return the value of t_order.MERCHANT_OPERATORID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public String getMerchantOperatorid() {
        return merchantOperatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_order.MERCHANT_OPERATORID
     *
     * @param merchantOperatorid the value for t_order.MERCHANT_OPERATORID
     *
     * @ibatorgenerated Fri May 29 12:16:00 VET 2009
     */
    public void setMerchantOperatorid(String merchantOperatorid) {
        this.merchantOperatorid = merchantOperatorid == null ? null : merchantOperatorid.trim();
    }

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
}
