package org.fudaa.dodico.corba.mathematiques;

/**
* org/fudaa/dodico/corba/mathematiques/IMathMatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/devel/fudaa/fudaa_devel/dodico/idl/general/mathematiques.idl
* mercredi 6 ao�t 2008 22 h 27 CEST
*/
public interface IMathMatrice extends IMathMatriceOperations, org.fudaa.dodico.corba.mathematiques.IMathematiques, org.omg.CORBA.portable.IDLEntity {
}
