package org.fudaa.dodico.corba.houle;

/**
* org/fudaa/dodico/corba/houle/IHouleSitePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/devel/fudaa/fudaa_devel/dodico/idl/metier/houle.idl
* mercredi 6 ao�t 2008 22 h 27 CEST
*/
public abstract class IHouleSitePOA extends org.omg.PortableServer.Servant implements org.fudaa.dodico.corba.houle.IHouleSiteOperations, org.omg.CORBA.portable.InvokeHandler {

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("carteHauteur", new java.lang.Integer(0));
        _methods.put("carteVitesseX", new java.lang.Integer(1));
        _methods.put("carteVitesseY", new java.lang.Integer(2));
        _methods.put("carteCoteSurfaceLibre", new java.lang.Integer(3));
        _methods.put("cartePression", new java.lang.Integer(4));
        _methods.put("carteDirectionOrthogonale", new java.lang.Integer(5));
        _methods.put("carteSXX", new java.lang.Integer(6));
        _methods.put("carteSYY", new java.lang.Integer(7));
        _methods.put("carteSXY", new java.lang.Integer(8));
        _methods.put("carteFX", new java.lang.Integer(9));
        _methods.put("carteFY", new java.lang.Integer(10));
        _methods.put("carteCambrure", new java.lang.Integer(11));
        _methods.put("carteCritereLinearite", new java.lang.Integer(12));
        _methods.put("carteCritereOndesLongues", new java.lang.Integer(13));
        _methods.put("carteNombreUrsel", new java.lang.Integer(14));
        _methods.put("carteLongueurOnde", new java.lang.Integer(15));
        _methods.put("carteHauteurMax", new java.lang.Integer(16));
        _methods.put("dispose", new java.lang.Integer(17));
        _methods.put("initialise", new java.lang.Integer(18));
        _methods.put("reconnecte", new java.lang.Integer(19));
        _methods.put("creeClone", new java.lang.Integer(20));
        _methods.put("moduleCorba", new java.lang.Integer(21));
        _methods.put("interfacesCorba", new java.lang.Integer(22));
        _methods.put("egale", new java.lang.Integer(23));
        _methods.put("codeHachage", new java.lang.Integer(24));
        _methods.put("enChaine", new java.lang.Integer(25));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method, org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null) throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        switch(__method.intValue()) {
            case 0:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteHauteur();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 1:
                {
                    double z = org.fudaa.dodico.corba.base.ReelHelper.read(in);
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteVitesseX(z);
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 2:
                {
                    double z = org.fudaa.dodico.corba.base.ReelHelper.read(in);
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteVitesseY(z);
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 3:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteCoteSurfaceLibre();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 4:
                {
                    double z = org.fudaa.dodico.corba.base.ReelHelper.read(in);
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.cartePression(z);
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 5:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteDirectionOrthogonale();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 6:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteSXX();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 7:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteSYY();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 8:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteSXY();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 9:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteFX();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 10:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteFY();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 11:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteCambrure();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 12:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteCritereLinearite();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 13:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteCritereOndesLongues();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 14:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteNombreUrsel();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 15:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteLongueurOnde();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 16:
                {
                    org.fudaa.dodico.corba.representation.ICarteSpectrale $result = null;
                    $result = this.carteHauteurMax();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.representation.ICarteSpectraleHelper.write(out, $result);
                    break;
                }
            case 17:
                {
                    this.dispose();
                    out = $rh.createReply();
                    break;
                }
            case 18:
                {
                    org.fudaa.dodico.corba.objet.IObjet o = org.fudaa.dodico.corba.objet.IObjetHelper.read(in);
                    this.initialise(o);
                    out = $rh.createReply();
                    break;
                }
            case 19:
                {
                    String nom = org.fudaa.dodico.corba.base.ChaineHelper.read(in);
                    this.reconnecte(nom);
                    out = $rh.createReply();
                    break;
                }
            case 20:
                {
                    org.fudaa.dodico.corba.objet.IObjet $result = null;
                    $result = this.creeClone();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.objet.IObjetHelper.write(out, $result);
                    break;
                }
            case 21:
                {
                    String $result = null;
                    $result = this.moduleCorba();
                    out = $rh.createReply();
                    out.write_string($result);
                    break;
                }
            case 22:
                {
                    String $result[] = null;
                    $result = this.interfacesCorba();
                    out = $rh.createReply();
                    org.fudaa.dodico.corba.base.VChaineHelper.write(out, $result);
                    break;
                }
            case 23:
                {
                    org.fudaa.dodico.corba.objet.IObjet o = org.fudaa.dodico.corba.objet.IObjetHelper.read(in);
                    boolean $result = false;
                    $result = this.egale(o);
                    out = $rh.createReply();
                    out.write_boolean($result);
                    break;
                }
            case 24:
                {
                    int $result = (int) 0;
                    $result = this.codeHachage();
                    out = $rh.createReply();
                    out.write_long($result);
                    break;
                }
            case 25:
                {
                    String $result = null;
                    $result = this.enChaine();
                    out = $rh.createReply();
                    out.write_string($result);
                    break;
                }
            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }
        return out;
    }

    private static String[] __ids = { "IDL:houle/IHouleSite:1.0", "IDL:houle/IHoule:1.0", "IDL:objet/IObjet:1.0" };

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public IHouleSite _this() {
        return IHouleSiteHelper.narrow(super._this_object());
    }

    public IHouleSite _this(org.omg.CORBA.ORB orb) {
        return IHouleSiteHelper.narrow(super._this_object(orb));
    }
}
