package ejb.objectmodel.administration;

import javax.ejb.*;

/**
 * Created May 26, 2003 6:23:02 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author vasu praveen
 */
public interface LocalACC_BUDGET_TRANSACTIONHome extends javax.ejb.EJBLocalHome {

    public ejb.objectmodel.administration.LocalACC_BUDGET_TRANSACTION findByPrimaryKey(ejb.objectmodel.administration.ACC_BUDGET_TRANSACTIONKey aKey) throws javax.ejb.FinderException;

    public LocalACC_BUDGET_TRANSACTION create(int libID, int serveID, int taID, java.sql.Timestamp taDate, java.lang.String taType, java.math.BigDecimal taAmt, java.lang.String budgetID, java.lang.String payslipNo, java.lang.String expenditureOrCommitted, java.lang.String entryID, java.sql.Timestamp entryDate) throws javax.ejb.CreateException;

    public int getMaxBudgetTransactionID(int libID);

    public LocalACC_BUDGET_TRANSACTION create(int libID, int budgetTaID, java.sql.Timestamp taDate, java.math.BigDecimal taAmt, java.lang.String taType, java.lang.String budgetID, java.lang.String committedOrExp, java.sql.Timestamp commitDate, java.sql.Timestamp committedDate, java.lang.String invoiceNo, java.lang.String payslipNo, java.lang.String swapBudgetID, java.lang.String entryID, java.sql.Timestamp entryDate) throws javax.ejb.CreateException;

    public LocalACC_BUDGET_TRANSACTION create(java.lang.Integer libID, java.lang.Integer budgetTaID, java.sql.Timestamp taDate, java.math.BigDecimal taAmt, java.lang.String taType, java.lang.String budgetID, java.lang.String committedOrExpenditure, java.sql.Timestamp commitDate, java.lang.String paySlipNumber, java.lang.String entryID, java.sql.Timestamp entryDate) throws javax.ejb.CreateException;

    public LocalACC_BUDGET_TRANSACTION createAddDeposit(java.lang.Integer library_Id, java.lang.Integer budget_Ta_Id, java.sql.Timestamp ta_Date, java.math.BigDecimal ta_Amt, java.lang.String ta_Type, java.lang.String budget_Id, java.lang.String committed_Or_Expenditure, java.lang.String entry_Id, java.sql.Timestamp entry_Date) throws javax.ejb.CreateException;

    public java.util.Collection findByBudgetTransactions(java.lang.Integer library_Id, java.lang.Integer budget_Ta_Id) throws javax.ejb.FinderException;

    public java.util.Vector getTransactionDetails(java.lang.String libid, java.lang.String budgetid);

    public java.util.Collection findByBudgetIdandEntryDate(java.lang.Integer library_Id, java.lang.String budget_Id, java.sql.Timestamp entry_Date) throws javax.ejb.FinderException;
}
