package ppsim.corba;

/**
* supp/corba/SuppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from c:/eclipse/workspace/supp/idl/server.idl
* Sunday, October 31, 2004 4:11:17 PM EET
*/
public final class PPSimHolder implements org.omg.CORBA.portable.Streamable {

    public ppsim.corba.PPSim value = null;

    public PPSimHolder() {
    }

    public PPSimHolder(ppsim.corba.PPSim initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = ppsim.corba.PPSimHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        ppsim.corba.PPSimHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return ppsim.corba.PPSimHelper.type();
    }
}
