package coursetimetable;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmoud
 */
public class System_Constants extends javax.swing.JFrame {

    /** Creates new form Admin_Main */
    connect c = new connect();

    procedures prc = new procedures();

    public ResultSet r;

    ExtraFunctions extra = new ExtraFunctions();

    String query;

    int ID;

    int check;

    int count;

    AddNewSemster frame;

    public System_Constants(AddNewSemster f) {
        this.setLocation(200, 100);
        this.setResizable(false);
        frame = f;
        initComponents();
        try {
            query = prc.get_Current_Year();
            r = c.connection(query);
            while (r.next()) {
                jLabel2.setText(r.getString(1));
            }
            query = prc.GetSystemStatus();
            r = c.connection(query);
            while (r.next()) {
                jTextField12.setText(r.getString(1));
                jTextField11.setText(r.getString(2));
                jTextField10.setText(r.getString(6));
                jTextField9.setText(r.getString(7));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR" + ex.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton48 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("Form");
        addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent evt) {
                Closing(evt);
            }
        });
        jPanel1.setName("jPanel1");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setName("jTabbedPane1");
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(coursetimetable.CourseTimeTableApp.class).getContext().getResourceMap(System_Constants.class);
        jButton49.setText(resourceMap.getString("jButton49.text"));
        jButton49.setToolTipText(resourceMap.getString("jButton49.toolTipText"));
        jButton49.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton49.setName("jButton49");
        jButton49.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton49MouseClicked(evt);
            }
        });
        jPanel3.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 110, 30));
        jLabel21.setText(resourceMap.getString("jLabel21.text"));
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel21.setName("jLabel21");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, 30));
        jTextField9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField9.setName("jTextField9");
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, 30));
        jTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField12.setName("jTextField12");
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, 30));
        jLabel30.setText(resourceMap.getString("jLabel30.text"));
        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel30.setName("jLabel30");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, 30));
        jButton48.setText(resourceMap.getString("jButton48.text"));
        jButton48.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton48.setName("jButton48");
        jButton48.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton48MouseClicked(evt);
            }
        });
        jPanel3.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 180, 30));
        jLabel28.setText(resourceMap.getString("jLabel28.text"));
        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel28.setName("jLabel28");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));
        jTextField11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField11.setName("jTextField11");
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 30));
        jLabel29.setText(resourceMap.getString("jLabel29.text"));
        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel29.setName("jLabel29");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, 30));
        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField10.setName("jTextField10");
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, 30));
        jLabel10.setIcon(resourceMap.getIcon("jLabel10.icon"));
        jLabel10.setName("jLabel10");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));
        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3);
        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 700, 480));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setName("jPanel7");
        jPanel7.setLayout(null);
        jLabel1.setFont(resourceMap.getFont("YearLabel.font"));
        jLabel1.setText(resourceMap.getString("YearLabel.text"));
        jLabel1.setName("YearLabel");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(10, 20, 140, 40);
        jLabel2.setFont(resourceMap.getFont("Yaer20_label.font"));
        jLabel2.setText(resourceMap.getString("Yaer20_label.text"));
        jLabel2.setName("Yaer20_label");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(150, 20, 90, 40);
        jLabel9.setIcon(resourceMap.getIcon("jLabel9.icon"));
        jLabel9.setText(resourceMap.getString("jLabel9.text"));
        jLabel9.setName("jLabel9");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(0, 0, 260, 70);
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 260, 70));
        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon"));
        jLabel3.setText(resourceMap.getString("jLabel3.text"));
        jLabel3.setName("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 840, 590));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        pack();
    }

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void jButton48MouseClicked(java.awt.event.MouseEvent evt) {
        if (!"".equals(jTextField10.getText()) && !"".equals(jTextField11.getText()) && !"".equals(jTextField12.getText()) && !"".equals(jTextField9.getText())) {
            try {
                int year = Integer.parseInt(jTextField12.getText());
                int semester = Integer.parseInt(jTextField11.getText());
                int weeks = Integer.parseInt(jTextField10.getText());
                int slots = Integer.parseInt(jTextField9.getText());
                query = prc.UpdateSystem(weeks, slots, semester, year);
                check = c.UpdateConnection(query);
                if (check == 1) {
                    JOptionPane.showMessageDialog(null, "Added Succefully", "Success Operation", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    frame.setVisible(true);
                } else JOptionPane.showMessageDialog(null, "Can't be Added", "Unsuccess Operation", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR" + ex.toString());
            }
        } else JOptionPane.showMessageDialog(this, "Please Complete All fields", "ERROR!!!", JOptionPane.OK_OPTION);
    }

    private void jButton49MouseClicked(java.awt.event.MouseEvent evt) {
        this.dispose();
        frame.setVisible(true);
    }

    private void Closing(java.awt.event.WindowEvent evt) {
        this.dispose();
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new System_Constants(null).setVisible(true);
            }
        });
    }

    private javax.swing.JButton jButton48;

    private javax.swing.JButton jButton49;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel10;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JLabel jLabel28;

    private javax.swing.JLabel jLabel29;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel30;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JTextField jTextField10;

    private javax.swing.JTextField jTextField11;

    private javax.swing.JTextField jTextField12;

    private javax.swing.JTextField jTextField9;
}
