package javanect.openni;

import com.sun.jna.Structure;

/**
 * <i>native declaration : XnTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XnYUV422DoublePixel extends Structure {

    public byte nU;

    public byte nY1;

    public byte nV;

    public byte nY2;

    public XnYUV422DoublePixel() {
        super();
    }

    /**
	 * @param nU C type : XnUInt8<br>
	 * @param nY1 C type : XnUInt8<br>
	 * @param nV C type : XnUInt8<br>
	 * @param nY2 C type : XnUInt8
	 */
    public XnYUV422DoublePixel(byte nU, byte nY1, byte nV, byte nY2) {
        super();
        this.nU = nU;
        this.nY1 = nY1;
        this.nV = nV;
        this.nY2 = nY2;
    }

    public static class ByReference extends XnYUV422DoublePixel implements Structure.ByReference {
    }

    ;

    public static class ByValue extends XnYUV422DoublePixel implements Structure.ByValue {
    }

    ;
}
