package net.wsnware.gui.canvas;

import net.wsnware.core.NetworkLayer;
import net.wsnware.gui.ComponentGui;
import javax.swing.JScrollPane;

/**
 * GUI form for NetworkLayer component encapsulating NetworkCanvas,
 * it displays the network layout on canvas.
 * 
 * @author  Alessandro Polo <contact@alessandropolo.name>
 * @version 0.1.0
 * @date    2011-05-17
 */
public class NetworkView extends javax.swing.JPanel implements ComponentGui {

    protected NetworkCanvas canvas = new NetworkCanvas();

    protected JScrollPane canvasScroller;

    public NetworkView() {
        initComponents();
        CanvasDefaults.NodeRendererDefault nRend = (CanvasDefaults.NodeRendererDefault) this.canvas.getRendererNode();
        this.jcmbNodeColorMode.setModel(new javax.swing.DefaultComboBoxModel(CanvasDefaults.NodeRendererDefault.NodeColorMode.values()));
        this.jcmbNodeColorMode.setSelectedItem(nRend.getMode());
        canvasScroller = new JScrollPane(canvas);
        canvasScroller.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        canvasScroller.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jtabOptions.insertTab("Canvas", null, canvasScroller, TOOL_TIP_TEXT_KEY, 0);
        jtabOptions.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        btnGroupColors = new javax.swing.ButtonGroup();
        jtabOptions = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jchkConnectionsDraw = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox();
        jsliderScale = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jchkShapeVariance = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jcmbNodeColorMode = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtabOptions.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Connections"));
        jchkConnectionsDraw.setSelected(true);
        jchkConnectionsDraw.setText("Draw neighbours' connections");
        jchkConnectionsDraw.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkConnectionsDrawActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(jchkConnectionsDraw).addContainerGap(137, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addComponent(jchkConnectionsDraw).addContainerGap(38, Short.MAX_VALUE)));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "X, Y", " " }));
        jComboBox2.setEnabled(false);
        jsliderScale.setMajorTickSpacing(100);
        jsliderScale.setMaximum(1000);
        jsliderScale.setMinimum(1);
        jsliderScale.setMinorTickSpacing(50);
        jsliderScale.setPaintTicks(true);
        jsliderScale.setValue(100);
        jsliderScale.addChangeListener(new javax.swing.event.ChangeListener() {

            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsliderScaleStateChanged(evt);
            }
        });
        jLabel2.setText("Space:");
        jLabel3.setText("Scale:");
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Shape"));
        jPanel2.setToolTipText("");
        jPanel2.setName("");
        jchkShapeVariance.setSelected(true);
        jchkShapeVariance.setText("Draw position variance ");
        jchkShapeVariance.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkShapeVarianceActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jchkShapeVariance).addContainerGap(175, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jchkShapeVariance).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jcmbNodeColorMode, 0, 318, Short.MAX_VALUE).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jcmbNodeColorMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(33, Short.MAX_VALUE)));
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup().addComponent(jLabel2).addGap(18, 18, 18).addComponent(jComboBox2, 0, 296, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup().addComponent(jLabel3).addGap(18, 18, 18).addComponent(jsliderScale, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)).addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(234, 234, 234)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3).addComponent(jsliderScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(15, Short.MAX_VALUE)));
        jtabOptions.addTab("Axis & Scale", jPanel5);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Fixed Anchor");
        jRadioButton2.setText("Node Anchor");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Center", "Top-Left", " " }));
        jLabel1.setText("Canvas Mapping:");
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addGroup(jPanel3Layout.createSequentialGroup().addComponent(jRadioButton2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jLabel1).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jRadioButton1)).addContainerGap()));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jRadioButton1).addGap(9, 9, 9).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jRadioButton2)).addGap(20, 20, 20).addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(254, Short.MAX_VALUE)));
        jtabOptions.addTab("Grid Anchors", jPanel3);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jtabOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jtabOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE));
    }

    private void jchkShapeVarianceActionPerformed(java.awt.event.ActionEvent evt) {
        CanvasDefaults.NodeRendererDefault nRend = (CanvasDefaults.NodeRendererDefault) this.canvas.getRendererNode();
        nRend.setDrawShapeVariance(jchkShapeVariance.isSelected());
    }

    private void jchkConnectionsDrawActionPerformed(java.awt.event.ActionEvent evt) {
        CanvasDefaults.NodeRendererDefault nRend = (CanvasDefaults.NodeRendererDefault) this.canvas.getRendererNode();
        nRend.setDrawConnections(jchkConnectionsDraw.isSelected());
    }

    private void jsliderScaleStateChanged(javax.swing.event.ChangeEvent evt) {
        CanvasDefaults.CanvasTransformDefault cTras = (CanvasDefaults.CanvasTransformDefault) this.canvas.getCanvasTransform();
        cTras.setScale((double) jsliderScale.getValue() / 10.0);
    }

    @Override
    public void setInstance(Object obj) {
        canvas.setInstance(obj);
    }

    @Override
    public Object getInstance() {
        return canvas.network;
    }

    @Override
    public Class[] getSupportedComponents() {
        return new Class[] { NetworkLayer.class };
    }

    @Override
    public String getPid() {
        return canvas.getPid();
    }

    @Override
    public void setPid(String pid) {
        canvas.setPid(pid);
    }

    public NetworkCanvas getCanvas() {
        return canvas;
    }

    public void setCanvas(NetworkCanvas canvas) {
        this.canvas = canvas;
    }

    public static void main(String args[]) {
    }

    private javax.swing.ButtonGroup btnGroupColors;

    private javax.swing.JComboBox jComboBox1;

    private javax.swing.JComboBox jComboBox2;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JRadioButton jRadioButton1;

    private javax.swing.JRadioButton jRadioButton2;

    private javax.swing.JSeparator jSeparator2;

    private javax.swing.JTextField jTextField1;

    private javax.swing.JCheckBox jchkConnectionsDraw;

    private javax.swing.JCheckBox jchkShapeVariance;

    private javax.swing.JComboBox jcmbNodeColorMode;

    private javax.swing.JSlider jsliderScale;

    private javax.swing.JTabbedPane jtabOptions;
}
