package com.tst.tstfsm.fsm.base;

/**
 * Generated by FSM Generator
 * Can be changed manually
 */
public class ConnectedEvent extends TestFSMBaseEvent {

    /**************************************************************************/
    ConnectedEvent() {
    }

    /**************************************************************************/
    void Process(TestFSMBaseState state) {
        state.Process(this);
    }
}
