package newgen.presentation.acquisitions;

import javax.help.*;

/**
 *
 * @author  Administrator
 */
public class CancelOrdersFrame extends javax.swing.JInternalFrame implements newgen.presentation.component.NewGenLibScreen {

    private static CancelOrdersFrame instance = null;

    private static CancelOrdersPanel cancelOrdersPanel = null;

    public static CancelOrdersFrame getInstance() {
        if (instance == null) {
            instance = new CancelOrdersFrame();
        }
        instance.reloadLocales();
        return instance;
    }

    /** Creates new form CancelOrdersFrame */
    public CancelOrdersFrame() {
        initComponents();
        HelpBroker helpbroker = newgen.presentation.NewGenMain.getAppletInstance().getHelpbroker();
        HelpSet helpset = newgen.presentation.NewGenMain.getAppletInstance().getHelpset();
        helpbroker.enableHelp(this, "CancelorderFrame", helpset);
        java.awt.event.ActionListener bhelpal = new CSH.DisplayHelpFromSource(helpbroker);
        this.bHelp.addActionListener(bhelpal);
        cancelOrdersPanel = new CancelOrdersPanel();
        this.jPanel1.add(cancelOrdersPanel);
        this.setSize(750, 500);
        newgen.presentation.NewGenMain.getAppletInstance().applyOrientation(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bCancelOrder = new javax.swing.JButton();
        bHelp = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("CancelOrders"));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        bCancelOrder.setMnemonic('o');
        bCancelOrder.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("CancelOrder"));
        bCancelOrder.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelOrderActionPerformed(evt);
            }
        });
        jPanel2.add(bCancelOrder);
        bHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newgen/images/help.gif")));
        bHelp.setMnemonic('h');
        jPanel2.add(bHelp);
        bCancel.setMnemonic('c');
        bCancel.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("Cancel"));
        bCancel.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel2.add(bCancel);
        bClose.setMnemonic('e');
        bClose.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("Close"));
        bClose.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });
        jPanel2.add(bClose);
        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);
        pack();
    }

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {
        cancelOrdersPanel.refreshScreen();
    }

    private void bCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {
        cancelOrdersPanel.cancelOrdersDetails();
    }

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    public void reloadLocales() {
        cancelOrdersPanel.reloadLocales();
        newgen.presentation.NewGenMain.getAppletInstance().applyOrientation(this);
        bCancelOrder.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("CancelOrder"));
        bCancel.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("Cancel"));
        bClose.setText(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("Close"));
        setTitle(newgen.presentation.NewGenMain.getAppletInstance().getMyResource().getString("CancelOrders"));
    }

    private javax.swing.JButton bCancel;

    private javax.swing.JButton bCancelOrder;

    private javax.swing.JButton bClose;

    private javax.swing.JButton bHelp;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;
}
