package org.ostion.siplacad2.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * PlanificacionDocenteActividad generated by hbm2java
 */
@Entity
@Table(name = "planificacion_docente_actividad", catalog = "siplacaddb", uniqueConstraints = @UniqueConstraint(columnNames = { "id_planificacion_docente", "id_actividad" }))
public class PlanificacionDocenteActividad implements java.io.Serializable {

    private Integer id;

    private Actividad actividad;

    private PlanificacionDocente planificacionDocente;

    private int horasAdministracion;

    private int horasInvestigacion;

    private int horasServicios;

    private int horasExtension;

    public PlanificacionDocenteActividad() {
    }

    public PlanificacionDocenteActividad(Actividad actividad, PlanificacionDocente planificacionDocente, int horasAdministracion, int horasInvestigacion, int horasServicios, int horasExtension) {
        this.actividad = actividad;
        this.planificacionDocente = planificacionDocente;
        this.horasAdministracion = horasAdministracion;
        this.horasInvestigacion = horasInvestigacion;
        this.horasServicios = horasServicios;
        this.horasExtension = horasExtension;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_actividad", nullable = false)
    @NotNull
    public Actividad getActividad() {
        return this.actividad;
    }

    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_planificacion_docente", nullable = false)
    @NotNull
    public PlanificacionDocente getPlanificacionDocente() {
        return this.planificacionDocente;
    }

    public void setPlanificacionDocente(PlanificacionDocente planificacionDocente) {
        this.planificacionDocente = planificacionDocente;
    }

    @Column(name = "horas_administracion", nullable = false)
    @NotNull
    public int getHorasAdministracion() {
        return this.horasAdministracion;
    }

    public void setHorasAdministracion(int horasAdministracion) {
        this.horasAdministracion = horasAdministracion;
    }

    @Column(name = "horas_investigacion", nullable = false)
    @NotNull
    public int getHorasInvestigacion() {
        return this.horasInvestigacion;
    }

    public void setHorasInvestigacion(int horasInvestigacion) {
        this.horasInvestigacion = horasInvestigacion;
    }

    @Column(name = "horas_servicios", nullable = false)
    @NotNull
    public int getHorasServicios() {
        return this.horasServicios;
    }

    public void setHorasServicios(int horasServicios) {
        this.horasServicios = horasServicios;
    }

    @Column(name = "horas_extension", nullable = false)
    @NotNull
    public int getHorasExtension() {
        return this.horasExtension;
    }

    public void setHorasExtension(int horasExtension) {
        this.horasExtension = horasExtension;
    }
}
