package com.amidasoft.lincat.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Scope;

/**
 * ServeisRecomanats generated by hbm2java
 */
@Entity
@Scope(ScopeType.CONVERSATION)
@Table(name = "serveis_recomanats")
public class ServeisRecomanats implements java.io.Serializable {

    private Integer id;

    private String nom;

    private String descripcio;

    private Set<Ventes> venteses = new HashSet<Ventes>(0);

    public ServeisRecomanats() {
    }

    public ServeisRecomanats(String nom, String descripcio) {
        this.nom = nom;
        this.descripcio = descripcio;
    }

    public ServeisRecomanats(String nom, String descripcio, Set<Ventes> venteses) {
        this.nom = nom;
        this.descripcio = descripcio;
        this.venteses = venteses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nom", nullable = false, length = 64)
    @NotNull
    @Length(max = 64)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "descripcio", nullable = false, length = 65535)
    @NotNull
    @Length(max = 65535)
    public String getDescripcio() {
        return this.descripcio;
    }

    public void setDescripcio(String descripcio) {
        this.descripcio = descripcio;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "serveisRecomanats")
    public Set<Ventes> getVenteses() {
        return this.venteses;
    }

    public void setVenteses(Set<Ventes> venteses) {
        this.venteses = venteses;
    }

    public int hashCode() {
        return this.getId();
    }

    public boolean equals(Object o) {
        boolean iguals = false;
        if (o instanceof ServeisRecomanats) {
            if (o == null || ((ServeisRecomanats) o).getId() == null || this.getId() == null) {
                iguals = false;
            }
            iguals = this.getId().equals(((ServeisRecomanats) o).getId());
        }
        return iguals;
    }
}
