/*
 * VolumeIdSerialIdSelectionDialog.java
 *
 * Created on July 30, 2003, 12:26 AM
 */

package newgen.presentation.opac.cataloguing;
import newgen.presentation.*;
/**
 *
 * @author  Administrator
 */
public class VolumeIdSerialIdSelectionDialog extends javax.swing.JDialog {
    
    /** Creates new form VolumeIdSerialIdSelectionDialog */
    public VolumeIdSerialIdSelectionDialog() {
        super();
        initComponents();
        String cols[] = {NewGenMain.getAppletInstance().getMyResource().getString("VolumeId"),NewGenMain.getAppletInstance().getMyResource().getString("VolumeNumber"),NewGenMain.getAppletInstance().getMyResource().getString("PartSubDivision")};
        dtmNonSerial = new javax.swing.table.DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        this.tableNonSerial.setModel(dtmNonSerial);
        
        String cols1[] = {NewGenMain.getAppletInstance().getMyResource().getString("SerialId"),NewGenMain.getAppletInstance().getMyResource().getString("VolumeNumber"),NewGenMain.getAppletInstance().getMyResource().getString("IssueNumber"),NewGenMain.getAppletInstance().getMyResource().getString("IssueYear")};
        dtmSerial = new javax.swing.table.DefaultTableModel(cols1, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        this.tableSerial.setModel(dtmSerial);
        this.setSize(520, 300);
        this.setLocation(NewGenMain.getAppletInstance().getLocation(520, 300));        
    }
    public void setTableData(String bibId, java.util.Hashtable ht) {
        this.bibid=bibId;
        if(bibId.equals("4")) {
            java.awt.CardLayout cl = (java.awt.CardLayout)jPanel1.getLayout();
            cl.show(jPanel1, "serial");
            
            java.util.Enumeration enum = ht.keys();
            while(enum.hasMoreElements()) {
                String key = enum.nextElement().toString();
                java.util.Vector v1 = (java.util.Vector)ht.get(key);
                
                Object[] r = new Object[4];
                r[0]=key;
                r[1]=v1.elementAt(0);
                r[2]=v1.elementAt(1);
                r[3]=v1.elementAt(2);
                dtmSerial.addRow(r);
            }
        }
        else {
            java.awt.CardLayout cl = (java.awt.CardLayout)jPanel1.getLayout();
            cl.show(jPanel1, "nonserial");
            
            java.util.Enumeration enum = ht.keys();
            while(enum.hasMoreElements()) {
                String key = enum.nextElement().toString();
                java.util.Vector v1 = (java.util.Vector)ht.get(key);
                
                Object[] r = new Object[3];
                r[0]=key;
                r[1]=v1.elementAt(0);
                r[2]=v1.elementAt(1);
                dtmNonSerial.addRow(r);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSerialVolumeNumber = new newgen.presentation.UnicodeTextField();
        jLabel2 = new javax.swing.JLabel();
        tfSerialIssueNumber = new newgen.presentation.UnicodeTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSerialIssueYear = new newgen.presentation.UnicodeTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSerial = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNonSerialVolumeNumber = new newgen.presentation.UnicodeTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNonSerialPartSubDivision = new newgen.presentation.UnicodeTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNonSerial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();

        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(NewGenMain.getAppletInstance().getMyResource().getString("VolumeNumber"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel5.add(jLabel1, gridBagConstraints);

        jPanel5.add(tfSerialVolumeNumber, new java.awt.GridBagConstraints());

        jLabel2.setText(NewGenMain.getAppletInstance().getMyResource().getString("IssueNumber"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel5.add(jLabel2, gridBagConstraints);

        tfSerialIssueNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSerialIssueNumberActionPerformed(evt);
            }
        });

        jPanel5.add(tfSerialIssueNumber, new java.awt.GridBagConstraints());

        jLabel3.setText(NewGenMain.getAppletInstance().getMyResource().getString("IssueYear"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel5.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel5.add(tfSerialIssueYear, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.BorderLayout());

        tableSerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableSerial);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, "serial");

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText(NewGenMain.getAppletInstance().getMyResource().getString("VolumeNumber"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel4, gridBagConstraints);

        jPanel7.add(tfNonSerialVolumeNumber, new java.awt.GridBagConstraints());

        jLabel5.setText(NewGenMain.getAppletInstance().getMyResource().getString("PartSubDivision"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel7.add(tfNonSerialPartSubDivision, gridBagConstraints);

        jPanel4.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel8.setLayout(new java.awt.BorderLayout());

        tableNonSerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableNonSerial);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, "nonserial");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bok.setMnemonic('o');
        bok.setText(NewGenMain.getAppletInstance().getMyResource().getString("Ok"));
        bok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bokActionPerformed(evt);
            }
        });

        jPanel2.add(bok);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newgen/images/help.gif")));
        jButton2.setMnemonic('h');
        jPanel2.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newgen/images/helpcsh.gif")));
        jPanel2.add(jButton3);

        bcancel.setMnemonic('c');
        bcancel.setText(NewGenMain.getAppletInstance().getMyResource().getString("Cancel"));
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });

        jPanel2.add(bcancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // Add your handling code here:
        this.setRetcode(1);
        this.dispose();
    }//GEN-LAST:event_bcancelActionPerformed

    private void bokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bokActionPerformed
        // Add your handling code here:
        if(this.bibid.equals("4"))
        {
            if(tableSerial.getSelectedRow()!=-1)
            {
                this.setVolumeSerialId(dtmSerial.getValueAt(tableSerial.getSelectedRow(), 0).toString());
                this.dispose();
                this.setRetcode(0);
            }
        }
        else
        {
            if(tableNonSerial.getSelectedRow()!=-1)
            {
                this.setVolumeSerialId(dtmNonSerial.getValueAt(tableNonSerial.getSelectedRow(), 0).toString());
                this.dispose();
                this.setRetcode(0);
            }            
        }
    }//GEN-LAST:event_bokActionPerformed
    
    private void tfSerialIssueNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSerialIssueNumberActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_tfSerialIssueNumberActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /** Getter for property volumeSerialId.
     * @return Value of property volumeSerialId.
     *
     */
    public java.lang.String getVolumeSerialId() {
        return volumeSerialId;
    }    
    
    /** Setter for property volumeSerialId.
     * @param volumeSerialId New value of property volumeSerialId.
     *
     */
    public void setVolumeSerialId(java.lang.String volumeSerialId) {
        this.volumeSerialId = volumeSerialId;
    }    
    
    /** Getter for property retcode.
     * @return Value of property retcode.
     *
     */
    public int getRetcode() {
        return retcode;
    }    
    
    /** Setter for property retcode.
     * @param retcode New value of property retcode.
     *
     */
    public void setRetcode(int retcode) {
        this.retcode = retcode;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bok;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableNonSerial;
    private javax.swing.JTable tableSerial;
    private newgen.presentation.UnicodeTextField tfNonSerialPartSubDivision;
    private newgen.presentation.UnicodeTextField tfNonSerialVolumeNumber;
    private newgen.presentation.UnicodeTextField tfSerialIssueNumber;
    private newgen.presentation.UnicodeTextField tfSerialIssueYear;
    private newgen.presentation.UnicodeTextField tfSerialVolumeNumber;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel dtmNonSerial;
    private javax.swing.table.DefaultTableModel dtmSerial;
    private String bibid="";
    private String volumeSerialId="";
    private int retcode=0;
}
