package edu.unibi.agbi.biodwh.entity.reactome;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReferenceEntity2ReferenceGroupCount generated by hbm2java
 */
@Entity(name = "reactome_reference_entity2reference_group_count")
@Table(name = "reactome_reference_entity2reference_group_count")
public class ReferenceEntity2ReferenceGroupCount implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 6599795649408263421L;

    private ReferenceEntity2ReferenceGroupCountId id;

    public ReferenceEntity2ReferenceGroupCount() {
    }

    public ReferenceEntity2ReferenceGroupCount(ReferenceEntity2ReferenceGroupCountId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "dbId", column = @Column(name = "DB_ID")), @AttributeOverride(name = "referenceGroupCountRank", column = @Column(name = "referenceGroupCount_rank")), @AttributeOverride(name = "referenceGroupCount", column = @Column(name = "referenceGroupCount")), @AttributeOverride(name = "referenceGroupCountClass", column = @Column(name = "referenceGroupCount_class", length = 64)) })
    public ReferenceEntity2ReferenceGroupCountId getId() {
        return this.id;
    }

    public void setId(ReferenceEntity2ReferenceGroupCountId id) {
        this.id = id;
    }
}
