package gemini.basic.model;

import static javax.persistence.GenerationType.IDENTITY;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Month generated by hbm2java
 */
@Entity
@Table(name = "g_month", catalog = "gemini")
public class Month extends AbstractDomain implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;

    private Integer version;

    private int month;

    private int year;

    private int startDate;

    private int endDate;

    private List<MonthlyPoint> monthlyPoints = new ArrayList<MonthlyPoint>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "month", nullable = false)
    public int getMonth() {
        return this.month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    @Column(name = "year", nullable = false)
    public int getYear() {
        return this.year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    @Column(name = "start_date", nullable = false)
    public int getStartDate() {
        return this.startDate;
    }

    public void setStartDate(int startDate) {
        this.startDate = startDate;
    }

    @Column(name = "end_date", nullable = false)
    public int getEndDate() {
        return this.endDate;
    }

    public void setEndDate(int endDate) {
        this.endDate = endDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "month")
    public List<MonthlyPoint> getMonthlyPoints() {
        return this.monthlyPoints;
    }

    public void setMonthlyPoints(List<MonthlyPoint> monthlyPoints) {
        this.monthlyPoints = monthlyPoints;
    }
}
