package backend.parser.aracyc.sink;

public class Publication {

    public static int count = 0;

    private final String pid;

    /**
 * A unique ID is generated by this object atomaticaly but is not the identifier in equals()

 * @param parserID used in the postfix of the CV for the ID
 */
    public Publication(String parserID) {
        pid = "PUB_" + count + "_" + parserID;
        count++;
    }

    public String getPid() {
        return pid;
    }
}
