package UI;

import Logic.*;

/**
 *
 * @author Mickaël
 */
public class ConnaitreReponseJDialog extends javax.swing.JDialog {

    RendezVous rdv;

    Utilisateur utilCourant;

    /** Creates new form ConnaitreReponseJDialog<br>
     * Exemple d'utilisation :<br>
     *  ConnaitreReponseJDialog crd = new ConnaitreReponseJDialog(this, unobjetInvitation, objetUtilisateurCourant);<br>
     *  crd.setVisible(true);<br>
     * @param parent
     * @param modal
     * @param rdv
     * @param utilCourant
     */
    public ConnaitreReponseJDialog(java.awt.Frame parent, boolean modal, RendezVous rdv, Utilisateur utilCourant) {
        super(parent, modal);
        this.rdv = rdv;
        this.utilCourant = utilCourant;
        this.setTitle("Objet : " + rdv.getObjet());
        initComponents();
        afficherReponse();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taReponses = new javax.swing.JTextArea();
        btnModifierRDV = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        taReponses.setColumns(20);
        taReponses.setEditable(false);
        taReponses.setRows(5);
        taReponses.setToolTipText("Etat des réponses pour ce rendez-vous");
        taReponses.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane1.setViewportView(taReponses);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE).addGap(29, 29, 29)));
        btnModifierRDV.setText("Modifier ce rendez-vous");
        btnModifierRDV.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierRDVActionPerformed(evt);
            }
        });
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(btnModifierRDV).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE).addComponent(btnFermer).addContainerGap()).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnFermer).addComponent(btnModifierRDV)).addContainerGap()));
        pack();
    }

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void btnModifierRDVActionPerformed(java.awt.event.ActionEvent evt) {
        ((PrincipalJFrame) this.getParent()).editerRDV(rdv);
        this.dispose();
    }

    private javax.swing.JButton btnFermer;

    private javax.swing.JButton btnModifierRDV;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTextArea taReponses;

    private void afficherReponse() {
        Invitation[] reponses = null;
        String messageReponse = null;
        DB.ChargerObjetLogic col;
        try {
            col = new DB.ChargerObjetLogic();
            reponses = col.getReponsesRDV(rdv);
        } catch (Exception ex) {
            System.out.println("Impossible d'enregistrer ce rendez-vous\nVeuillez contacter un administrateur");
            return;
        }
        for (Invitation reponse : reponses) {
            if (reponse.getAcceptation() == null) messageReponse = " n'a pas répondu"; else if (reponse.getAcceptation() == true) messageReponse = " a accepté"; else if (reponse.getAcceptation() == false) messageReponse = " a refusé";
            if (reponse.isRepondu() && (reponse.getCommentaire() != null)) taReponses.append(reponse.getInvite().toString() + messageReponse + " (" + reponse.getCommentaire() + ")\n"); else taReponses.append(reponse.getInvite().toString() + messageReponse + "\n");
        }
    }
}
