package ejb.objectmodel.administration;

/**
 * Created Oct 17, 2003 6:50:23 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author Administrator
 */
public final class ACC_CREDIT_NOTE_TRANSACTIONKey implements java.io.Serializable {

    public java.lang.Integer library_Id;

    public java.lang.Integer credit_Ta_Id;

    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(java.lang.Object otherOb) {
        if (this == otherOb) {
            return true;
        }
        if (!(otherOb instanceof ejb.objectmodel.administration.ACC_CREDIT_NOTE_TRANSACTIONKey)) {
            return false;
        }
        ejb.objectmodel.administration.ACC_CREDIT_NOTE_TRANSACTIONKey other = (ejb.objectmodel.administration.ACC_CREDIT_NOTE_TRANSACTIONKey) otherOb;
        return ((library_Id == null ? other.library_Id == null : library_Id.equals(other.library_Id)) && (credit_Ta_Id == null ? other.credit_Ta_Id == null : credit_Ta_Id.equals(other.credit_Ta_Id)));
    }

    /**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        return ((library_Id == null ? 0 : library_Id.hashCode()) ^ (credit_Ta_Id == null ? 0 : credit_Ta_Id.hashCode()));
    }
}
