package com.spr.to;

/**
 * ProjGpArt generated by hbm2java
 */
public class ProjGpArt extends BaseTO implements java.io.Serializable {

    private long projArtId;

    private ProjectType projectType;

    private ProjArtifact projArtifact;

    private Long artId;

    public ProjGpArt() {
    }

    public long getProjArtId() {
        return this.projArtId;
    }

    public void setProjArtId(long projArtId) {
        this.projArtId = projArtId;
    }

    public ProjectType getProjectType() {
        return this.projectType;
    }

    public void setProjectType(ProjectType projectType) {
        this.projectType = projectType;
    }

    public ProjArtifact getProjArtifact() {
        return this.projArtifact;
    }

    public void setProjArtifact(ProjArtifact projArtifact) {
        this.projArtifact = projArtifact;
    }

    public Long getArtId() {
        return this.artId;
    }

    public void setArtId(Long artId) {
        this.artId = artId;
    }
}
