package edu.unibi.agbi.biodwh.entity.kegg.kgml;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KeggKgmlEntryReaction generated by hbm2java
 */
@Entity(name = "kegg_kgml_entry_reaction")
@Table(name = "kegg_kgml_entry_reaction")
public class KeggKgmlEntryReaction implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = -5657047603028385013L;

    private KeggKgmlEntryReactionId id;

    private KeggKgmlEntry keggKgmlEntry;

    public KeggKgmlEntryReaction() {
    }

    public KeggKgmlEntryReaction(KeggKgmlEntryReactionId id, KeggKgmlEntry keggKgmlEntry) {
        this.id = id;
        this.keggKgmlEntry = keggKgmlEntry;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "entryId", column = @Column(name = "entry_id", nullable = false)), @AttributeOverride(name = "reaction", column = @Column(name = "reaction", nullable = false)) })
    public KeggKgmlEntryReactionId getId() {
        return this.id;
    }

    public void setId(KeggKgmlEntryReactionId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "entry_id", nullable = false, insertable = false, updatable = false)
    public KeggKgmlEntry getKeggKgmlEntry() {
        return this.keggKgmlEntry;
    }

    public void setKeggKgmlEntry(KeggKgmlEntry keggKgmlEntry) {
        this.keggKgmlEntry = keggKgmlEntry;
    }
}
