package library.corba;

/**
* library/corba/DocumentDetailsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/CORBALibrary.idl
* Monday, July 12, 2010 5:38:18 PM CEST
*/
public abstract class DocumentDetailsHelper {

    private static String _id = "IDL:library/corba/DocumentDetails:1.0";

    public static void insert(org.omg.CORBA.Any a, library.corba.DocumentDetails that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static library.corba.DocumentDetails extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;

    private static boolean __active = false;

    public static synchronized org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            synchronized (org.omg.CORBA.TypeCode.class) {
                if (__typeCode == null) {
                    if (__active) {
                        return org.omg.CORBA.ORB.init().create_recursive_tc(_id);
                    }
                    __active = true;
                    org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[11];
                    org.omg.CORBA.TypeCode _tcOf_members0 = null;
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_boolean);
                    _members0[0] = new org.omg.CORBA.StructMember("isNull", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_boolean);
                    _members0[1] = new org.omg.CORBA.StructMember("isDocumentTypeNull", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_ulonglong);
                    _members0[2] = new org.omg.CORBA.StructMember("id", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[3] = new org.omg.CORBA.StructMember("author", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[4] = new org.omg.CORBA.StructMember("description", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_ulong);
                    _members0[5] = new org.omg.CORBA.StructMember("documentID", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_sequence_tc(0, _tcOf_members0);
                    _members0[6] = new org.omg.CORBA.StructMember("documentType", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[7] = new org.omg.CORBA.StructMember("notes", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[8] = new org.omg.CORBA.StructMember("publisher", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[9] = new org.omg.CORBA.StructMember("serie", _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_wstring_tc(0);
                    _members0[10] = new org.omg.CORBA.StructMember("title", _tcOf_members0, null);
                    __typeCode = org.omg.CORBA.ORB.init().create_struct_tc(library.corba.DocumentDetailsHelper.id(), "DocumentDetails", _members0);
                    __active = false;
                }
            }
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static library.corba.DocumentDetails read(org.omg.CORBA.portable.InputStream istream) {
        library.corba.DocumentDetails value = new library.corba.DocumentDetails();
        value.isNull = istream.read_boolean();
        value.isDocumentTypeNull = istream.read_boolean();
        value.id = istream.read_ulonglong();
        value.author = istream.read_wstring();
        value.description = istream.read_wstring();
        value.documentID = istream.read_ulong();
        int _len0 = istream.read_long();
        value.documentType = new String[_len0];
        for (int _o1 = 0; _o1 < value.documentType.length; ++_o1) value.documentType[_o1] = istream.read_wstring();
        value.notes = istream.read_wstring();
        value.publisher = istream.read_wstring();
        value.serie = istream.read_wstring();
        value.title = istream.read_wstring();
        return value;
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, library.corba.DocumentDetails value) {
        ostream.write_boolean(value.isNull);
        ostream.write_boolean(value.isDocumentTypeNull);
        ostream.write_ulonglong(value.id);
        ostream.write_wstring(value.author);
        ostream.write_wstring(value.description);
        ostream.write_ulong(value.documentID);
        ostream.write_long(value.documentType.length);
        for (int _i0 = 0; _i0 < value.documentType.length; ++_i0) ostream.write_wstring(value.documentType[_i0]);
        ostream.write_wstring(value.notes);
        ostream.write_wstring(value.publisher);
        ostream.write_wstring(value.serie);
        ostream.write_wstring(value.title);
    }
}
