package org.fudaa.dodico.corba.evenement;

/**
* org/fudaa/dodico/corba/evenement/IObjetEventSender.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/devel/fudaa/fudaa_devel/dodico/idl/general/evenement.idl
* mercredi 6 ao�t 2008 22 h 27 CEST
*/
public interface IObjetEventSender extends IObjetEventSenderOperations, org.fudaa.dodico.corba.objet.IObjet, org.omg.CORBA.portable.IDLEntity {
}
