package org.hsnr.didac.om;

import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Nov 24 10:42:09 CET 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class TurbineRolePermission extends org.hsnr.didac.om.BaseTurbineRolePermission implements Persistent {
}
