package org.fudaa.dodico.corba.hiswa;

/**
* org/fudaa/dodico/corba/hiswa/SResultatsLigneHiswaTableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/devel/fudaa/fudaa_devel/dodico/idl/code/hiswa.idl
* mercredi 6 ao�t 2008 22 h 26 CEST
*/
public final class SResultatsLigneHiswaTableHolder implements org.omg.CORBA.portable.Streamable {

    public org.fudaa.dodico.corba.hiswa.SResultatsLigneHiswaTable value = null;

    public SResultatsLigneHiswaTableHolder() {
    }

    public SResultatsLigneHiswaTableHolder(org.fudaa.dodico.corba.hiswa.SResultatsLigneHiswaTable initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = org.fudaa.dodico.corba.hiswa.SResultatsLigneHiswaTableHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        org.fudaa.dodico.corba.hiswa.SResultatsLigneHiswaTableHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return org.fudaa.dodico.corba.hiswa.SResultatsLigneHiswaTableHelper.type();
    }
}
