package verisoft.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import verisoft.BE.*;

/**
 *
 * @author gginet
 */
public class FrmDetalleFirmante extends javax.swing.JDialog {

    /** Creates new form FrmDetalleFirmante */
    Firmante firmante = null;

    Usuario usuarioSesion = null;

    Image imgFirma = null;

    Image imgHuella = null;

    public FrmDetalleFirmante(java.awt.Frame parent, Firmante firmante, Usuario usuarioSesion) {
        super(parent, true);
        initComponents();
        this.firmante = firmante;
        this.usuarioSesion = usuarioSesion;
        llenarDatos();
        obtenerImagenes();
        dibujar();
    }

    private void llenarDatos() {
        if (firmante != null) {
            jTDni.setText(String.valueOf(firmante.getDni()));
            jTNombres.setText(firmante.getNombres());
            jTApePaterno.setText(firmante.getAppaterno());
            jTApeMaterno.setText(firmante.getApmaterno());
            jTEstado.setText(firmante.getEstado().getDescripcion());
        }
    }

    private void dibujar() {
        try {
            ImageIcon iconFirma = new ImageIcon(imgFirma);
            JLFirma.setIcon(iconFirma);
            ImageIcon iconHuella = new ImageIcon(imgHuella);
            jLHuella.setIcon(iconHuella);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    private void obtenerImagenes() {
        try {
            imgFirma = (Image) (convertirAImagen(firmante.getFirma()));
            imgHuella = (Image) (convertirAImagen(firmante.getHuelladigital()));
        } catch (Exception ex) {
        }
    }

    private BufferedImage convertirAImagen(byte[] byteImagen) {
        try {
            InputStream in = new ByteArrayInputStream(byteImagen);
            return ImageIO.read(in);
        } catch (Exception ex) {
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTDni = new javax.swing.JTextField();
        jTNombres = new javax.swing.JTextField();
        jTApePaterno = new javax.swing.JTextField();
        jTApeMaterno = new javax.swing.JTextField();
        jTEstado = new javax.swing.JTextField();
        jLDNI = new javax.swing.JLabel();
        jLnombres = new javax.swing.JLabel();
        jLApellidoPaterno = new javax.swing.JLabel();
        jLApellidoMaterno = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jPFirma = new javax.swing.JPanel();
        JLFirma = new javax.swing.JLabel();
        jPHuella = new javax.swing.JPanel();
        jLHuella = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form");
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(verisoft.GUI.VerisoftApp.class).getContext().getResourceMap(FrmDetalleFirmante.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), resourceMap.getString("jPanel1.border.title")));
        jPanel1.setName("jPanel1");
        jTDni.setEditable(false);
        jTDni.setName("jTDni");
        jTNombres.setEditable(false);
        jTNombres.setName("jTNombres");
        jTApePaterno.setEditable(false);
        jTApePaterno.setName("jTApePaterno");
        jTApeMaterno.setEditable(false);
        jTApeMaterno.setName("jTApeMaterno");
        jTEstado.setEditable(false);
        jTEstado.setName("jTEstado");
        jLDNI.setText(resourceMap.getString("jLDNI.text"));
        jLDNI.setName("jLDNI");
        jLnombres.setText(resourceMap.getString("jLnombres.text"));
        jLnombres.setName("jLnombres");
        jLApellidoPaterno.setText(resourceMap.getString("jLApellidoPaterno.text"));
        jLApellidoPaterno.setName("jLApellidoPaterno");
        jLApellidoMaterno.setText(resourceMap.getString("jLApellidoMaterno.text"));
        jLApellidoMaterno.setName("jLApellidoMaterno");
        jLEstado.setText(resourceMap.getString("jLEstado.text"));
        jLEstado.setName("jLEstado");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(76, 76, 76).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLDNI).addComponent(jLnombres).addComponent(jLApellidoPaterno).addComponent(jLApellidoMaterno).addComponent(jLEstado)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(12, 12, 12).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE).addComponent(jTApeMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE).addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(97, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()))));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGap(21, 21, 21).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLDNI)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLnombres)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLApellidoPaterno)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLApellidoMaterno)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLEstado)).addContainerGap(40, Short.MAX_VALUE)));
        jPFirma.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Firma"));
        jPFirma.setFocusable(false);
        jPFirma.setName("jPFirma");
        JLFirma.setName("JLFirma");
        javax.swing.GroupLayout jPFirmaLayout = new javax.swing.GroupLayout(jPFirma);
        jPFirma.setLayout(jPFirmaLayout);
        jPFirmaLayout.setHorizontalGroup(jPFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPFirmaLayout.createSequentialGroup().addGap(21, 21, 21).addComponent(JLFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(37, Short.MAX_VALUE)));
        jPFirmaLayout.setVerticalGroup(jPFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPFirmaLayout.createSequentialGroup().addComponent(JLFirma, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE).addContainerGap()));
        jPHuella.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Huella"));
        jPHuella.setName("jPHuella");
        jLHuella.setText(resourceMap.getString("jLHuella.text"));
        jLHuella.setName("jLHuella");
        javax.swing.GroupLayout jPHuellaLayout = new javax.swing.GroupLayout(jPHuella);
        jPHuella.setLayout(jPHuellaLayout);
        jPHuellaLayout.setHorizontalGroup(jPHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPHuellaLayout.createSequentialGroup().addContainerGap().addComponent(jLHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE).addContainerGap()));
        jPHuellaLayout.setVerticalGroup(jPHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHuellaLayout.createSequentialGroup().addComponent(jLHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE).addContainerGap()));
        jBSalir.setIcon(resourceMap.getIcon("jBSalir.icon"));
        jBSalir.setText(resourceMap.getString("jBSalir.text"));
        jBSalir.setName("jBSalir");
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE).addComponent(jPHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(22, 22, 22))))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPHuella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(12, 12, 12)));
        pack();
    }

    private void Salir(java.awt.event.MouseEvent evt) {
        this.dispose();
    }

    private javax.swing.JLabel JLFirma;

    private javax.swing.JButton jBSalir;

    private javax.swing.JLabel jLApellidoMaterno;

    private javax.swing.JLabel jLApellidoPaterno;

    private javax.swing.JLabel jLDNI;

    private javax.swing.JLabel jLEstado;

    private javax.swing.JLabel jLHuella;

    private javax.swing.JLabel jLnombres;

    private javax.swing.JPanel jPFirma;

    private javax.swing.JPanel jPHuella;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JTextField jTApeMaterno;

    private javax.swing.JTextField jTApePaterno;

    private javax.swing.JTextField jTDni;

    private javax.swing.JTextField jTEstado;

    private javax.swing.JTextField jTNombres;
}
