package iec61970.generation.generationdynamics.validation;

import iec61970.generation.generationdynamics.CombustionTurbine;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link iec61970.generation.generationdynamics.HeatRecoveryBoiler}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HeatRecoveryBoilerValidator {

    boolean validate();

    boolean validateSteamSupplyRating2(String value);

    boolean validateCombustionTurbines(EList<CombustionTurbine> value);
}
