package org.omg.CosEventChannelAdmin;

/**
* org/omg/CosEventChannelAdmin/EventChannel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* Friday, December 17, 2004 1:02:22 PM EST
*/
public interface EventChannel extends EventChannelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
}
