package org.unicef.doc.ibis.nut;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 * <p>Not used.</p>
 */
public class MainView extends FrameView {

    public MainView(SingleFrameApplication app) {
        super(app);
        initComponents();
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String) (evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer) (evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = Main.getApplication().getMainFrame();
            aboutBox = new MainAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        Main.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dpMain = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        homepageElementsPanel1 = new org.unicef.doc.ibis.nut.HomepageElementsPanel();
        textPanel1 = new org.unicef.doc.ibis.nut.TextPanel();
        imageDisplayPanel1 = new org.unicef.doc.ibis.nut.ImageDisplayPanel();
        audioPanel1 = new org.unicef.doc.ibis.nut.AudioPanel();
        videoPanel1 = new org.unicef.doc.ibis.nut.VideoPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        homepageElements1 = new org.unicef.doc.ibis.nut.persistence.HomepageElements();
        mainPanel.setName("mainPanel");
        mainPanel.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setName("jScrollPane1");
        dpMain.setAutoscrolls(true);
        dpMain.setName("dpMain");
        dpMain.setPreferredSize(new java.awt.Dimension(6400, 4800));
        dpMain.setRequestFocusEnabled(false);
        jInternalFrame1.setName("jInternalFrame1");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new java.awt.GridBagLayout());
        jTabbedPane1.setName("jTabbedPane1");
        homepageElementsPanel1.setName("homepageElementsPanel1");
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.unicef.doc.ibis.nut.Main.class).getContext().getResourceMap(MainView.class);
        jTabbedPane1.addTab(resourceMap.getString("homepageElementsPanel1.TabConstraints.tabTitle"), homepageElementsPanel1);
        textPanel1.setName("textPanel1");
        jTabbedPane1.addTab(resourceMap.getString("textPanel1.TabConstraints.tabTitle"), textPanel1);
        imageDisplayPanel1.setName("imageDisplayPanel1");
        jTabbedPane1.addTab(resourceMap.getString("imageDisplayPanel1.TabConstraints.tabTitle"), imageDisplayPanel1);
        audioPanel1.setName("audioPanel1");
        jTabbedPane1.addTab(resourceMap.getString("audioPanel1.TabConstraints.tabTitle"), audioPanel1);
        videoPanel1.setName("videoPanel1");
        jTabbedPane1.addTab(resourceMap.getString("videoPanel1.TabConstraints.tabTitle"), videoPanel1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jInternalFrame1.getContentPane().add(jTabbedPane1, gridBagConstraints);
        jInternalFrame1.setBounds(30, 70, 600, 360);
        dpMain.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jScrollPane1.setViewportView(dpMain);
        mainPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        menuBar.setName("menuBar");
        fileMenu.setText(resourceMap.getString("fileMenu.text"));
        fileMenu.setName("fileMenu");
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text"));
        jMenuItem1.setName("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);
        jMenu1.setText(resourceMap.getString("jMenu1.text"));
        jMenu1.setName("jMenu1");
        fileMenu.add(jMenu1);
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.unicef.doc.ibis.nut.Main.class).getContext().getActionMap(MainView.class, this);
        jMenuItem2.setAction(actionMap.get("openAction"));
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text"));
        jMenuItem2.setName("jMenuItem2");
        fileMenu.add(jMenuItem2);
        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text"));
        jMenuItem3.setName("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem3);
        jMenu3.setText(resourceMap.getString("jMenu3.text"));
        jMenu3.setName("jMenu3");
        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text"));
        jMenuItem6.setName("jMenuItem6");
        jMenu3.add(jMenuItem6);
        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text"));
        jMenuItem7.setName("jMenuItem7");
        jMenu3.add(jMenuItem7);
        fileMenu.add(jMenu3);
        jSeparator1.setName("jSeparator1");
        fileMenu.add(jSeparator1);
        exitMenuItem.setAction(actionMap.get("quit"));
        exitMenuItem.setName("exitMenuItem");
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
        jMenu4.setText(resourceMap.getString("jMenu4.text"));
        jMenu4.setName("jMenu4");
        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text"));
        jMenuItem8.setName("jMenuItem8");
        jMenu4.add(jMenuItem8);
        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text"));
        jMenuItem9.setName("jMenuItem9");
        jMenu4.add(jMenuItem9);
        jMenuItem10.setText(resourceMap.getString("jMenuItem10.text"));
        jMenuItem10.setName("jMenuItem10");
        jMenu4.add(jMenuItem10);
        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text"));
        jMenuItem11.setName("jMenuItem11");
        jMenu4.add(jMenuItem11);
        menuBar.add(jMenu4);
        jMenu2.setText(resourceMap.getString("jMenu2.text"));
        jMenu2.setName("jMenu2");
        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text"));
        jMenuItem4.setName("jMenuItem4");
        jMenu2.add(jMenuItem4);
        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text"));
        jMenuItem5.setName("jMenuItem5");
        jMenu2.add(jMenuItem5);
        menuBar.add(jMenu2);
        helpMenu.setText(resourceMap.getString("helpMenu.text"));
        helpMenu.setName("helpMenu");
        aboutMenuItem.setAction(actionMap.get("showAboutBox"));
        aboutMenuItem.setName("aboutMenuItem");
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
        statusPanel.setName("statusPanel");
        statusPanelSeparator.setName("statusPanelSeparator");
        statusMessageLabel.setName("statusMessageLabel");
        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel");
        progressBar.setName("progressBar");
        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE).addGroup(statusPanelLayout.createSequentialGroup().addContainerGap().addComponent(statusMessageLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 744, Short.MAX_VALUE).addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(statusAnimationLabel).addContainerGap()));
        statusPanelLayout.setVerticalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(statusPanelLayout.createSequentialGroup().addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(statusMessageLabel).addComponent(statusAnimationLabel).addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(3, 3, 3)));
        jPanel1.setName("jPanel1");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100, Short.MAX_VALUE));
        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private org.unicef.doc.ibis.nut.AudioPanel audioPanel1;

    private javax.swing.JDesktopPane dpMain;

    private org.unicef.doc.ibis.nut.persistence.HomepageElements homepageElements1;

    private org.unicef.doc.ibis.nut.HomepageElementsPanel homepageElementsPanel1;

    private org.unicef.doc.ibis.nut.ImageDisplayPanel imageDisplayPanel1;

    private javax.swing.JInternalFrame jInternalFrame1;

    private javax.swing.JMenu jMenu1;

    private javax.swing.JMenu jMenu2;

    private javax.swing.JMenu jMenu3;

    private javax.swing.JMenu jMenu4;

    private javax.swing.JMenuItem jMenuItem1;

    private javax.swing.JMenuItem jMenuItem10;

    private javax.swing.JMenuItem jMenuItem11;

    private javax.swing.JMenuItem jMenuItem2;

    private javax.swing.JMenuItem jMenuItem3;

    private javax.swing.JMenuItem jMenuItem4;

    private javax.swing.JMenuItem jMenuItem5;

    private javax.swing.JMenuItem jMenuItem6;

    private javax.swing.JMenuItem jMenuItem7;

    private javax.swing.JMenuItem jMenuItem8;

    private javax.swing.JMenuItem jMenuItem9;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JSeparator jSeparator1;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JPanel mainPanel;

    private javax.swing.JMenuBar menuBar;

    private javax.swing.JProgressBar progressBar;

    private javax.swing.JLabel statusAnimationLabel;

    private javax.swing.JLabel statusMessageLabel;

    private javax.swing.JPanel statusPanel;

    private org.unicef.doc.ibis.nut.TextPanel textPanel1;

    private org.unicef.doc.ibis.nut.VideoPanel videoPanel1;

    private final Timer messageTimer;

    private final Timer busyIconTimer;

    private final Icon idleIcon;

    private final Icon[] busyIcons = new Icon[15];

    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
