package se.mdh.mrtc.save.taEditor.validation;

/**
 * A sample validator interface for {@link se.mdh.mrtc.save.taEditor.StandardEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StandardEdgeValidator {

    boolean validate();
}
