package unbbayes.prs.mebn.ssbn.extension;

import unbbayes.prs.mebn.ssbn.ISSBNGenerator;

/**
 * This is a part of plugin framework for MEBN module.
 * This interface builds an instance of {@link ISSBNGenerator}.
 * It must provide a default constructor with no arguments.
 * @author Shou Matsumoto
 *
 */
public interface ISSBNGeneratorBuilder {

    /**
	 * Builds an instance of {@link ISSBNGenerator}
	 * mostly using the parameters passed from {@link #setName(String)}
	 * @return instance of {@link ISSBNGenerator}
	 * @throws InstantiationException when we fail to build an instance
	 */
    public ISSBNGenerator buildSSBNGenerator() throws InstantiationException;

    /**
	 * Obtains a name for the {@link ISSBNGenerator} (SSBN algorithm) 
	 * to be generated by this builder.
	 * This is used by the program to display a name to a user.
	 * @return a name
	 */
    public String getName();

    /**
	 * Obtains a name for the {@link ISSBNGenerator} (SSBN algorithm) 
	 * to be generated by this builder.
	 * This is used by the program to display a name to a user.
	 * @param name : name of the KB
	 */
    public void setName(String name);
}
