package iec61970.generation.generationdynamics.validation;

import iec61970.generation.generationdynamics.BoilerControlMode;

/**
 * A sample validator interface for {@link iec61970.generation.generationdynamics.FossilSteamSupply}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FossilSteamSupplyValidator {

    boolean validate();

    boolean validateAuxPowerVersusFrequency(String value);

    boolean validateAuxPowerversusVoltage(String value);

    boolean validateControlIC(String value);

    boolean validateBoilerControlMode(BoilerControlMode value);

    boolean validateControlErrorBiasP(String value);

    boolean validateControlPC(String value);

    boolean validateControlPEB(String value);

    boolean validateControlPED(String value);

    boolean validateControlTC(String value);

    boolean validateFeedWaterIG(String value);

    boolean validateFeedWaterPG(String value);

    boolean validateFeedWaterTC(String value);

    boolean validateFuelDemandLimit(String value);

    boolean validateFuelSupplyDelay(String value);

    boolean validateMechPowerSensorLag(String value);

    boolean validateFuelSupplyTC(String value);

    boolean validateMaxErrorRateP(String value);

    boolean validateMinErrorRateP(String value);

    boolean validatePressureCtrlDG(String value);

    boolean validatePressureCtrlIG(String value);

    boolean validatePressureCtrlPG(String value);

    boolean validatePressureFeedback(String value);

    boolean validateSuperHeater1Capacity(String value);

    boolean validateSuperHeater2Capacity(String value);

    boolean validateSuperHeaterPipePD(String value);

    boolean validateThrottlePressureSP(String value);
}
