package org.fudaa.dodico.corba.representation;

/**
* org/fudaa/dodico/corba/representation/IHistoireHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/devel/fudaa/fudaa_devel/dodico/idl/metier/representation.idl
* mercredi 6 ao�t 2008 22 h 27 CEST
*/
public final class IHistoireHolder implements org.omg.CORBA.portable.Streamable {

    public org.fudaa.dodico.corba.representation.IHistoire value = null;

    public IHistoireHolder() {
    }

    public IHistoireHolder(org.fudaa.dodico.corba.representation.IHistoire initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = org.fudaa.dodico.corba.representation.IHistoireHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        org.fudaa.dodico.corba.representation.IHistoireHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return org.fudaa.dodico.corba.representation.IHistoireHelper.type();
    }
}
