public class WifiNative {
    static final int BLUETOOTH_COEXISTENCE_MODE_ENABLED = 0;
    static final int BLUETOOTH_COEXISTENCE_MODE_DISABLED = 1;
    static final int BLUETOOTH_COEXISTENCE_MODE_SENSE = 2;
    public native static String getErrorString(int errorCode);
    public native static boolean loadDriver();
    public native static boolean unloadDriver();
    public native static boolean startSupplicant();
    public native static boolean stopSupplicant();
    public native static boolean connectToSupplicant();
    public native static void closeSupplicantConnection();
    public native static boolean pingCommand();
    public native static boolean scanCommand(boolean forceActive);
    public native static boolean setScanModeCommand(boolean setActive);
    public native static String listNetworksCommand();
    public native static int addNetworkCommand();
    public native static boolean setNetworkVariableCommand(int netId, String name, String value);
    public native static String getNetworkVariableCommand(int netId, String name);
    public native static boolean removeNetworkCommand(int netId);
    public native static boolean enableNetworkCommand(int netId, boolean disableOthers);
    public native static boolean disableNetworkCommand(int netId);
    public native static boolean reconnectCommand();
    public native static boolean reassociateCommand();
    public native static boolean disconnectCommand();
    public native static String statusCommand();
    public native static int getRssiCommand();
    public native static int getRssiApproxCommand();
    public native static int getLinkSpeedCommand();
    public native static String getMacAddressCommand();
    public native static String scanResultsCommand();
    public native static boolean startDriverCommand();
    public native static boolean stopDriverCommand();
    public native static boolean startPacketFiltering();
    public native static boolean stopPacketFiltering();
    public native static boolean setPowerModeCommand(int mode);
    public native static boolean setNumAllowedChannelsCommand(int numChannels);
    public native static int getNumAllowedChannelsCommand();
    public native static boolean setBluetoothCoexistenceModeCommand(int mode);
    public native static boolean setBluetoothCoexistenceScanModeCommand(boolean setCoexScanMode);
    public native static boolean saveConfigCommand();
    public native static boolean reloadConfigCommand();
    public native static boolean setScanResultHandlingCommand(int mode);
    public native static boolean addToBlacklistCommand(String bssid);
    public native static boolean clearBlacklistCommand();
    public native static boolean doDhcpRequest(DhcpInfo results);
    public native static String getDhcpError();
    public native static String waitForEvent();
}
