public class TestHelper_Connection1 implements Connection {
    public void clearWarnings() throws SQLException {
    }
    public void close() throws SQLException {
    }
    public void commit() throws SQLException {
    }
    public Statement createStatement() throws SQLException {
        return null;
    }
    public Statement createStatement(int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        return null;
    }
    public Statement createStatement(int resultSetType, int resultSetConcurrency)
            throws SQLException {
        return null;
    }
    public boolean getAutoCommit() throws SQLException {
        return false;
    }
    public String getCatalog() throws SQLException {
        return null;
    }
    public int getHoldability() throws SQLException {
        return 0;
    }
    public DatabaseMetaData getMetaData() throws SQLException {
        return null;
    }
    public int getTransactionIsolation() throws SQLException {
        return 0;
    }
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        return null;
    }
    public SQLWarning getWarnings() throws SQLException {
        return null;
    }
    public boolean isClosed() throws SQLException {
        return false;
    }
    public boolean isReadOnly() throws SQLException {
        return false;
    }
    public String nativeSQL(String sql) throws SQLException {
        return null;
    }
    public CallableStatement prepareCall(String sql, int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        return null;
    }
    public CallableStatement prepareCall(String sql, int resultSetType,
            int resultSetConcurrency) throws SQLException {
        return null;
    }
    public CallableStatement prepareCall(String sql) throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency) throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
            throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql, String[] columnNames)
            throws SQLException {
        return null;
    }
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return null;
    }
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    }
    public void rollback() throws SQLException {
    }
    public void rollback(Savepoint savepoint) throws SQLException {
    }
    public void setAutoCommit(boolean autoCommit) throws SQLException {
    }
    public void setCatalog(String catalog) throws SQLException {
    }
    public void setHoldability(int holdability) throws SQLException {
    }
    public void setReadOnly(boolean readOnly) throws SQLException {
    }
    public Savepoint setSavepoint() throws SQLException {
        return null;
    }
    public Savepoint setSavepoint(String name) throws SQLException {
        return null;
    }
    public void setTransactionIsolation(int level) throws SQLException {
    }
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    }
}
